// AUTO-GENERATED by scripts/build.py from content.yaml -- DO NOT EDIT.
// To add a paper or talk, edit content.yaml and run: python3 scripts/build.py

export const research_data = [
  {
    "id": "vistas",
    "title": "Vistas: A Visualization Interface for Particle Collision Simulations",
    "date": "2026-06-17",
    "authors": "Benoît Assi, Christian Bierlich, Rikab Gambhir, Phil Ilten, Tony Menzo, Stephen Mrenna, Manuel Szewc, Michael K. Wilkinson, Jure Zupan",
    "img": "assets/img/vistas.png",
    "blurb": "We introduce Vistas, a tool for visualizing high-energy particle physics collisions simulated by the Pythia Monte-Carlo event generator. Particles produced from each of these stages are represented as lines in an interactive three-dimensional graph structure, where each line is along the direction of its particle's three-momentum vector. The event can be rotated, translated and zoomed, and details for each particle can be accessed by selecting the relevant particle line. Additionally, particle lines from all stages of the simulation can be toggled on and off and can be filtered by particle-level kinematic selection requirements. This interactive environment provides an intuitive interpretation of Pythia simulation output, including detailed features such as color flow, beam remnants, and multiple parton interactions, making it a useful tool in physics education settings, from outreach activities to graduate particle-physics courses.",
    "abstract": "",
    "tags": [
      "hadronization",
      "ml",
      "statistics"
    ],
    "featured": false,
    "joke": false,
    "status": "preprint",
    "bibtex": "@article{Assi:2026xih,\n    author = \"Assi, Benoit and Bierlich, Christan and Gambhir, Rikab and Ilten, Philip and Menzo, Tony and Mrenna, Stephen and Szewc, Manuel and Wilkinson, Michael K. and Youssef, Ahmed and Zupan, Jure\",\n    title = \"{Vistas: A Visualization Interface for Particle Collision Simulations}\",\n    eprint = \"2606.19524\",\n    archivePrefix = \"arXiv\",\n    primaryClass = \"physics.ed-ph\",\n    reportNumber = \"FERMILAB-PUB-26-0384-CSAID, MCNET-26-15\",\n    month = \"6\",\n    year = \"2026\"\n}",
    "links": [
      {
        "text": "INSPIRE-HEP",
        "href": "https://inspirehep.net/literature?q=arxiv:2606.19524"
      },
      {
        "text": "arXiv 2606.19524",
        "href": "https://arxiv.org/abs/2606.19524"
      }
    ],
    "talks": [],
    "citations": [
      {
        "month": "2026-06",
        "count": 0
      }
    ],
    "citations_excl_self": [
      {
        "month": "2026-06",
        "count": 0
      }
    ],
    "citations_total": 0,
    "citations_total_excl_self": 0,
    "citation_start": "2026-06"
  },
  {
    "id": "hdsense",
    "title": "HDSense: An efficient method for ranking observable sensitivity",
    "date": "2026-02-02",
    "authors": "Benoît Assi, Christian Bierlich, Rikab Gambhir, Phil Ilten, Tony Menzo, Stephen Mrenna, Manuel Szewc, Michael K. Wilkinson, Jure Zupan",
    "img": "assets/img/hdsense.png",
    "blurb": "We introduce the High-Dimensional Sensitivity (HDSense) score, a computationally efficient metric for ranking observable sets using only one-dimensional histograms. We apply HDSense to rank a set observables in terms of their constraining power with respect to five parameters of the Lund string model of hadronization implemented in Pythia using simulated leptonic collider events at the Z pole.",
    "abstract": "",
    "tags": [
      "hadronization",
      "ml",
      "statistics"
    ],
    "featured": false,
    "joke": false,
    "status": "preprint",
    "bibtex": "@inproceedings{Assi:2026wyo,\n    author = \"Assi, Beno{\\^\\i}t and Bierlich, Christian and Gambhir, Rikab and Ilten, Phil and Menzo, Tony and Mrenna, Stephen and Szewc, Manuel and Wilkinson, Michael K. and Zupan, Jure\",\n    title = \"{HDSense: An efficient method for ranking observable sensitivity}\",\n    eprint = \"2602.01509\",\n    archivePrefix = \"arXiv\",\n    primaryClass = \"hep-ph\",\n    reportNumber = \"FERMILAB-PUB-26-0034-CSAID\",\n    month = \"2\",\n    year = \"2026\"\n}",
    "links": [
      {
        "text": "INSPIRE-HEP",
        "href": "https://inspirehep.net/literature?q=arxiv:2602.01509"
      },
      {
        "text": "arXiv 2602.01509",
        "href": "https://arxiv.org/abs/2602.01509"
      }
    ],
    "talks": [
      "hd-sense-an-efficient-method-for-ranking-2026-03-09"
    ],
    "citations": [
      {
        "month": "2026-02",
        "count": 0
      },
      {
        "month": "2026-03",
        "count": 1
      }
    ],
    "citations_excl_self": [
      {
        "month": "2026-02",
        "count": 0
      }
    ],
    "citations_total": 1,
    "citations_total_excl_self": 0,
    "citation_start": "2026-02"
  },
  {
    "id": "rdf",
    "title": "Resummed Distribution Functions: Making Perturbation Theory Positive and Normalized",
    "date": "2025-12-05",
    "authors": "Rikab Gambhir, Radha Mastandrea",
    "img": "assets/img/rdf.png",
    "blurb": "We propose a framework, the Resummed Distribution Function (RDF), that, given a fixed-order perturbative calculation for an observable to some finite order in αsαs​, will ``resum'' the expression in a way that is guaranteed to match the original expression order-by-order and be positive, normalized, and finite. The RDF also enables a more direct notion of perturbative uncertainties, as we can directly vary higher-order parameters and treat them as nuisance parameters. We demonstrate the power of the RDF ansatz by matching to thrust to O(αs3) and extracting αs​ with perturbative uncertainties by fitting the RDF to ALEPH data.",
    "abstract": "",
    "tags": [
      "qcd",
      "statistics",
      "perturbation-theory"
    ],
    "featured": true,
    "joke": false,
    "status": "preprint",
    "bibtex": "@article{Gambhir:2025lka,\n    author = \"Gambhir, Rikab and Mastandrea, Radha\",\n    title = \"{Resummed Distribution Functions: Making Perturbation Theory Positive and Normalized}\",\n    eprint = \"2512.04160\",\n    archivePrefix = \"arXiv\",\n    primaryClass = \"hep-ph\",\n    month = \"12\",\n    year = \"2025\"\n}",
    "links": [
      {
        "text": "INSPIRE-HEP",
        "href": "https://inspirehep.net/literature?q=arxiv:2512.04160"
      },
      {
        "text": "arXiv 2512.04160",
        "href": "https://arxiv.org/abs/2512.04160"
      }
    ],
    "talks": [
      "resummed-distribution-functions-making-p-2026-04-30",
      "resummed-distribution-functions-making-p-2026-04-02",
      "re-normalizing-flows-taming-logs-and-per-2025-07-30",
      "re-normalizing-flows-taming-logs-and-per-2024-11-05"
    ],
    "citations": [
      {
        "month": "2025-12",
        "count": 0
      },
      {
        "month": "2026-06",
        "count": 1
      }
    ],
    "citations_excl_self": [
      {
        "month": "2025-12",
        "count": 0
      },
      {
        "month": "2026-06",
        "count": 1
      }
    ],
    "citations_total": 1,
    "citations_total_excl_self": 1,
    "citation_start": "2025-12"
  },
  {
    "id": "pareto",
    "title": "The Pareto Frontier of Resilient Jet Tagging",
    "date": "2025-09-23",
    "authors": "Rikab Gambhir, Matt LeBlanc, Yuanchen Zhou",
    "img": "assets/img/pareto.png",
    "blurb": "We explore the trade-off between performance and resilience in jet tagging. We show that more ``complex'' models, while achieving a higher AUC on jet tagging, are more simulation dependent and this can lead to real downstream uncertainties that diminish their percieved performance advantage over simpler models.",
    "abstract": "",
    "tags": [
      "ml",
      "jets",
      "robustness"
    ],
    "featured": false,
    "joke": false,
    "status": "preprint",
    "bibtex": "@inproceedings{Gambhir:2025xim,\n    author = \"Gambhir, Rikab and LeBlanc, Matt and Zhou, Yuanchen\",\n    title = \"{The Pareto Frontier of Resilient Jet Tagging}\",\n    booktitle = \"{39th Annual Conference on Neural Information Processing Systems}: {Includes Machine Learning and the Physical Sciences (ML4PS)}\",\n    eprint = \"2509.19431\",\n    archivePrefix = \"arXiv\",\n    primaryClass = \"hep-ph\",\n    reportNumber = \"MIT-CTP 5929\",\n    month = \"9\",\n    year = \"2025\"\n}",
    "links": [
      {
        "text": "INSPIRE-HEP",
        "href": "https://inspirehep.net/literature?q=arxiv:2509.19431"
      },
      {
        "text": "arXiv 2509.19431",
        "href": "https://arxiv.org/abs/2509.19431"
      }
    ],
    "talks": [
      "the-pareto-frontier-of-resilient-jet-tag-2025-08-21"
    ],
    "citations": [
      {
        "month": "2025-09",
        "count": 1
      },
      {
        "month": "2025-10",
        "count": 3
      },
      {
        "month": "2025-12",
        "count": 4
      },
      {
        "month": "2026-04",
        "count": 5
      }
    ],
    "citations_excl_self": [
      {
        "month": "2025-09",
        "count": 1
      },
      {
        "month": "2025-10",
        "count": 3
      },
      {
        "month": "2026-04",
        "count": 4
      }
    ],
    "citations_total": 5,
    "citations_total_excl_self": 4,
    "citation_start": "2025-09"
  },
  {
    "id": "april-fools-2025",
    "title": "A Search for ``New Physics'', ``Beyond the Standard Model''",
    "date": "2025-04-01",
    "authors": "Rikab Gambhir",
    "img": "assets/img/jester.png",
    "blurb": "In this distinguished work, I search for ``new physics'' and ``beyond the Standard Model'' &mdash; and find them.",
    "abstract": "",
    "tags": [],
    "featured": false,
    "joke": true,
    "status": "preprint",
    "bibtex": "@article{Gambhir:2025gjs,\n    author = \"Gambhir, Rikab\",\n    title = \"{A Search for ''New Physics'' ''Beyond the Standard Model'' in Open Data with Machine Learning}\",\n    eprint = \"2503.22790\",\n    archivePrefix = \"arXiv\",\n    primaryClass = \"hep-ph\",\n    month = \"3\",\n    year = \"2025\"\n}",
    "links": [
      {
        "text": "INSPIRE-HEP",
        "href": "https://inspirehep.net/literature?q=arxiv:2503.22790"
      },
      {
        "text": "arXiv 2503.22790",
        "href": "https://arxiv.org/abs/2503.22790"
      }
    ],
    "talks": [],
    "citations": [],
    "citations_excl_self": [],
    "citations_total": 0,
    "citations_total_excl_self": 0,
    "citation_start": "2025-04"
  },
  {
    "id": "upsilons",
    "title": "Isolating Unisolated Upsilons with Anomaly Detection in CMS Open Data",
    "date": "2025-02-19",
    "authors": "Rikab Gambhir, Radha Mastandrea, Ben Nachman, Jesse Thaler",
    "img": "assets/img/upsilons.png",
    "blurb": "We develop the first study of anti-isolated Upsilon decays in proton-proton collisions, using anomaly detection to separate signal from background in CMS Open Data. We, for the first time, present a successful application of anomaly detection to find a nontrivial signal in real collider data. We also develop a new method for improved sensitivity using full likelihood reweighting.",
    "abstract": "",
    "tags": [
      "anomaly-detection",
      "ml",
      "open-data",
      "cms"
    ],
    "featured": true,
    "joke": false,
    "status": "refereed",
    "bibtex": "@article{Gambhir:2025afb,\n    author = \"Gambhir, Rikab and Mastandrea, Radha and Nachman, Benjamin and Thaler, Jesse\",\n    title = \"{Isolating Unisolated Upsilons with Anomaly Detection in CMS Open Data}\",\n    eprint = \"2502.14036\",\n    archivePrefix = \"arXiv\",\n    primaryClass = \"hep-ph\",\n    reportNumber = \"MIT-CTP 5843\",\n    doi = \"10.1103/vvv3-5kkl\",\n    journal = \"Phys. Rev. Lett.\",\n    volume = \"135\",\n    number = \"2\",\n    pages = \"021902\",\n    year = \"2025\"\n}",
    "links": [
      {
        "text": "INSPIRE-HEP",
        "href": "https://inspirehep.net/literature?q=arxiv:2502.14036"
      },
      {
        "text": "arXiv 2502.14036",
        "href": "https://arxiv.org/abs/2502.14036"
      },
      {
        "text": "Phys. Rev. Lett. 135, 021902",
        "href": "https://journals.aps.org/prl/abstract/10.1103/vvv3-5kkl"
      },
      {
        "text": "GitHub",
        "href": "https://github.com/hep-lbdl/dimuonAD/"
      }
    ],
    "talks": [
      "likelihood-based-reweighting-for-improve-2025-06-18",
      "isolating-unisolated-upsilons-with-anoma-2025-05-20"
    ],
    "citations": [
      {
        "month": "2025-02",
        "count": 2
      },
      {
        "month": "2025-03",
        "count": 3
      },
      {
        "month": "2025-04",
        "count": 4
      },
      {
        "month": "2025-05",
        "count": 6
      },
      {
        "month": "2025-06",
        "count": 7
      },
      {
        "month": "2025-07",
        "count": 8
      },
      {
        "month": "2025-10",
        "count": 10
      },
      {
        "month": "2025-11",
        "count": 11
      },
      {
        "month": "2025-12",
        "count": 14
      },
      {
        "month": "2026-01",
        "count": 16
      },
      {
        "month": "2026-03",
        "count": 18
      },
      {
        "month": "2026-04",
        "count": 19
      },
      {
        "month": "2026-05",
        "count": 21
      }
    ],
    "citations_excl_self": [
      {
        "month": "2025-02",
        "count": 2
      },
      {
        "month": "2025-04",
        "count": 3
      },
      {
        "month": "2025-06",
        "count": 4
      },
      {
        "month": "2025-10",
        "count": 5
      },
      {
        "month": "2025-11",
        "count": 6
      },
      {
        "month": "2025-12",
        "count": 7
      },
      {
        "month": "2026-01",
        "count": 8
      },
      {
        "month": "2026-05",
        "count": 10
      }
    ],
    "citations_total": 21,
    "citations_total_excl_self": 10,
    "citation_start": "2025-02"
  },
  {
    "id": "specter",
    "title": "SPECTER: efficient evaluation of the spectral EMD",
    "date": "2024-10-07",
    "authors": "Rikab Gambhir, Andrew Larkoski, Jesse Thaler",
    "img": "assets/img/specter.png",
    "blurb": "We develop \"SPECTER\", an extremely fast code framework for evaluating the spectral EMD. We also use the Spectral EMD to define a new set of geometric observables, analogous to SHAPER [see below!]",
    "abstract": "",
    "tags": [
      "optimal-transport",
      "jets",
      "ml"
    ],
    "featured": false,
    "joke": false,
    "status": "refereed",
    "bibtex": "@article{Gambhir:2024ndc,\n    author = \"Gambhir, Rikab and Larkoski, Andrew J. and Thaler, Jesse\",\n    title = \"{SPECTER: efficient evaluation of the spectral EMD}\",\n    eprint = \"2410.05379\",\n    archivePrefix = \"arXiv\",\n    primaryClass = \"hep-ph\",\n    reportNumber = \"MIT-CTP 5771\",\n    doi = \"10.1007/JHEP12(2024)219\",\n    journal = \"JHEP\",\n    volume = \"12\",\n    pages = \"219\",\n    year = \"2025\"\n}",
    "links": [
      {
        "text": "INSPIRE-HEP",
        "href": "https://inspirehep.net/literature?q=arxiv:2410.05379"
      },
      {
        "text": "arXiv 2410.05379",
        "href": "https://arxiv.org/abs/2410.05379"
      },
      {
        "text": "J. High Energ. Phys. 2024, 219",
        "href": "https://link.springer.com/article/10.1007/JHEP12(2024)219"
      },
      {
        "text": "GitHub",
        "href": "https://github.com/rikab/SPECTER"
      }
    ],
    "talks": [
      "specter-efficient-evaluation-of-the-spec-2024-08-15",
      "specter-efficient-evaluation-of-the-spec-2024-07-31",
      "specter-efficient-evaluation-of-the-spec-2023-11-08"
    ],
    "citations": [
      {
        "month": "2024-10",
        "count": 1
      },
      {
        "month": "2025-01",
        "count": 3
      },
      {
        "month": "2025-03",
        "count": 5
      },
      {
        "month": "2025-04",
        "count": 6
      },
      {
        "month": "2025-05",
        "count": 7
      },
      {
        "month": "2025-06",
        "count": 8
      },
      {
        "month": "2025-09",
        "count": 9
      },
      {
        "month": "2025-11",
        "count": 10
      },
      {
        "month": "2025-12",
        "count": 11
      }
    ],
    "citations_excl_self": [
      {
        "month": "2024-10",
        "count": 1
      },
      {
        "month": "2025-01",
        "count": 2
      },
      {
        "month": "2025-06",
        "count": 3
      },
      {
        "month": "2025-09",
        "count": 4
      },
      {
        "month": "2025-11",
        "count": 5
      },
      {
        "month": "2025-12",
        "count": 6
      }
    ],
    "citations_total": 11,
    "citations_total_excl_self": 6,
    "citation_start": "2024-10"
  },
  {
    "id": "moments",
    "title": "Moments of Clarity: Streamlining Latent Spaces in Machine Learning using Moment Pooling",
    "date": "2024-03-13",
    "authors": "Rikab Gambhir, Athis Osathapan, Jesse Thaler",
    "img": "assets/img/moments.png",
    "blurb": "We propose \"Moment Pooling\", a multivariate-moment generalisation of Deep-Sets that slashes latent dimensions while preserving—and sometimes improving—performance. Demonstrated on quark–gluon jet classification.",
    "abstract": "",
    "tags": [
      "ml",
      "jets",
      "interpretability"
    ],
    "featured": false,
    "joke": false,
    "status": "refereed",
    "bibtex": "@article{Gambhir:2024dtf,\n    author = \"Gambhir, Rikab and Osathapan, Athis and Thaler, Jesse\",\n    title = \"{Streamlining latent spaces in machine learning using moment pooling}\",\n    eprint = \"2403.08854\",\n    archivePrefix = \"arXiv\",\n    primaryClass = \"hep-ph\",\n    reportNumber = \"MIT-CTP 5689\",\n    doi = \"10.1103/PhysRevD.110.074020\",\n    journal = \"Phys. Rev. D\",\n    volume = \"110\",\n    number = \"7\",\n    pages = \"074020\",\n    year = \"2024\"\n}",
    "links": [
      {
        "text": "INSPIRE-HEP",
        "href": "https://inspirehep.net/literature?q=arxiv:2403.08854"
      },
      {
        "text": "arXiv 2403.08854",
        "href": "https://arxiv.org/abs/2403.08854"
      },
      {
        "text": "Phys. Rev. D 110, 074020",
        "href": "https://doi.org/10.1103/PhysRevD.110.074020"
      },
      {
        "text": "GitHub",
        "href": "https://github.com/rikab/MomentAnalysis"
      }
    ],
    "talks": [
      "moments-of-clarity-in-machine-learning-f-2025-06-11",
      "moments-of-clarity-in-machine-learning-f-2025-03-12",
      "moments-of-clarity-in-machine-learning-f-2024-12-18",
      "moments-of-clarity-in-machine-learning-f-2024-10-18",
      "moments-of-clarity-in-machine-learning-f-2024-10-11",
      "moments-of-clarity-in-jet-physics-with-m-2024-09-24",
      "moments-of-clarity-in-machine-learning-f-2024-05-28",
      "moment-pooling-performance-interpretabil-2023-08-02",
      "moment-pooling-performance-interpretabil-2023-04-17"
    ],
    "citations": [
      {
        "month": "2024-03",
        "count": 1
      },
      {
        "month": "2024-04",
        "count": 2
      },
      {
        "month": "2024-10",
        "count": 3
      },
      {
        "month": "2025-02",
        "count": 5
      },
      {
        "month": "2025-05",
        "count": 7
      },
      {
        "month": "2025-10",
        "count": 9
      },
      {
        "month": "2026-02",
        "count": 10
      }
    ],
    "citations_excl_self": [
      {
        "month": "2024-03",
        "count": 1
      },
      {
        "month": "2024-04",
        "count": 2
      },
      {
        "month": "2024-10",
        "count": 3
      },
      {
        "month": "2025-02",
        "count": 5
      },
      {
        "month": "2025-05",
        "count": 6
      },
      {
        "month": "2025-10",
        "count": 8
      },
      {
        "month": "2026-02",
        "count": 9
      }
    ],
    "citations_total": 10,
    "citations_total_excl_self": 9,
    "citation_start": "2024-03"
  },
  {
    "id": "seeing-double",
    "title": "Seeing Double: Calibrating Two Jets at Once",
    "date": "2024-02-21",
    "authors": "Rikab Gambhir, Benjamin Nachman",
    "img": "assets/img/Seeing_Double.png",
    "blurb": "Exploits momentum-conservation correlations between dijets to improve CMS jet-energy calibration by 3–5 %, equivalent to a ~35 % quadrature improvement in resolution.",
    "abstract": "",
    "tags": [
      "calibration",
      "ml",
      "cms"
    ],
    "featured": false,
    "joke": false,
    "status": "refereed",
    "bibtex": "@article{Gambhir:2024tgs,\n    author = \"Gambhir, Rikab and Nachman, Benjamin\",\n    title = \"{Calibrating two jets at once}\",\n    eprint = \"2402.14067\",\n    archivePrefix = \"arXiv\",\n    primaryClass = \"hep-ph\",\n    reportNumber = \"MIT-CTP 5680\",\n    doi = \"10.1103/PhysRevD.110.076015\",\n    journal = \"Phys. Rev. D\",\n    volume = \"110\",\n    number = \"7\",\n    pages = \"076015\",\n    year = \"2024\"\n}",
    "links": [
      {
        "text": "INSPIRE-HEP",
        "href": "https://inspirehep.net/literature?q=arxiv:2402.14067"
      },
      {
        "text": "arXiv 2402.14067",
        "href": "https://arxiv.org/abs/2402.14067"
      },
      {
        "text": "Phys. Rev. D 110, 076015",
        "href": "https://doi.org/10.1103/PhysRevD.110.076015"
      },
      {
        "text": "GitHub",
        "href": "https://github.com/rikab/SeeingDouble"
      }
    ],
    "talks": [],
    "citations": [
      {
        "month": "2024-02",
        "count": 0
      },
      {
        "month": "2024-04",
        "count": 1
      },
      {
        "month": "2024-06",
        "count": 2
      },
      {
        "month": "2025-05",
        "count": 3
      },
      {
        "month": "2025-12",
        "count": 4
      }
    ],
    "citations_excl_self": [
      {
        "month": "2024-02",
        "count": 0
      },
      {
        "month": "2024-06",
        "count": 1
      },
      {
        "month": "2025-12",
        "count": 2
      }
    ],
    "citations_total": 4,
    "citations_total_excl_self": 2,
    "citation_start": "2024-02"
  },
  {
    "id": "muon-beam-dump",
    "title": "The New Physics Case for Beam-Dump Experiments with Accelerated Muon Beams",
    "date": "2023-10-24",
    "authors": "Cari Cesarotti, Rikab Gambhir",
    "img": "assets/img/beam_dump.png",
    "blurb": "Shows that even low-energy muon beam-dumps can open unexplored BSM parameter space from 10 GeV up to a few TeV.",
    "abstract": "",
    "tags": [
      "bsm",
      "muons",
      "future-colliders"
    ],
    "featured": false,
    "joke": false,
    "status": "refereed",
    "bibtex": "@article{Cesarotti:2023sje,\n    author = \"Cesarotti, Cari and Gambhir, Rikab\",\n    title = \"{The new physics case for beam-dump experiments with accelerated muon beams}\",\n    eprint = \"2310.16110\",\n    archivePrefix = \"arXiv\",\n    primaryClass = \"hep-ph\",\n    reportNumber = \"MIT-CTP 5606\",\n    doi = \"10.1007/JHEP05(2024)283\",\n    journal = \"JHEP\",\n    volume = \"05\",\n    pages = \"283\",\n    year = \"2024\"\n}",
    "links": [
      {
        "text": "INSPIRE-HEP",
        "href": "https://inspirehep.net/literature?q=arxiv:2310.16110"
      },
      {
        "text": "arXiv 2310.16110",
        "href": "https://arxiv.org/abs/2310.16110"
      },
      {
        "text": "J. High Energ. Phys. 2024, 283",
        "href": "https://doi.org/10.1007/JHEP05(2024)283"
      },
      {
        "text": "GitHub",
        "href": "https://github.com/rikab/MuonBeamDump"
      }
    ],
    "talks": [
      "the-new-physics-case-for-muon-beam-dump--2024-05-16",
      "the-new-physics-case-for-muon-beam-dump--2024-03-19"
    ],
    "citations": [
      {
        "month": "2023-10",
        "count": 0
      },
      {
        "month": "2023-11",
        "count": 1
      },
      {
        "month": "2023-12",
        "count": 2
      },
      {
        "month": "2024-05",
        "count": 3
      },
      {
        "month": "2024-07",
        "count": 5
      },
      {
        "month": "2024-09",
        "count": 7
      },
      {
        "month": "2024-10",
        "count": 8
      },
      {
        "month": "2024-12",
        "count": 11
      },
      {
        "month": "2025-01",
        "count": 13
      },
      {
        "month": "2025-03",
        "count": 14
      },
      {
        "month": "2025-04",
        "count": 16
      },
      {
        "month": "2025-05",
        "count": 17
      },
      {
        "month": "2025-06",
        "count": 18
      },
      {
        "month": "2025-07",
        "count": 19
      },
      {
        "month": "2025-09",
        "count": 21
      },
      {
        "month": "2025-10",
        "count": 22
      },
      {
        "month": "2025-11",
        "count": 23
      },
      {
        "month": "2025-12",
        "count": 24
      },
      {
        "month": "2026-02",
        "count": 25
      },
      {
        "month": "2026-04",
        "count": 27
      },
      {
        "month": "2026-06",
        "count": 28
      }
    ],
    "citations_excl_self": [
      {
        "month": "2023-10",
        "count": 0
      },
      {
        "month": "2023-12",
        "count": 1
      },
      {
        "month": "2024-05",
        "count": 2
      },
      {
        "month": "2024-07",
        "count": 3
      },
      {
        "month": "2024-09",
        "count": 5
      },
      {
        "month": "2024-10",
        "count": 6
      },
      {
        "month": "2024-12",
        "count": 9
      },
      {
        "month": "2025-01",
        "count": 11
      },
      {
        "month": "2025-04",
        "count": 12
      },
      {
        "month": "2025-06",
        "count": 13
      },
      {
        "month": "2025-07",
        "count": 14
      },
      {
        "month": "2025-09",
        "count": 16
      },
      {
        "month": "2025-10",
        "count": 17
      },
      {
        "month": "2025-11",
        "count": 18
      },
      {
        "month": "2025-12",
        "count": 19
      },
      {
        "month": "2026-02",
        "count": 20
      },
      {
        "month": "2026-04",
        "count": 22
      },
      {
        "month": "2026-06",
        "count": 23
      }
    ],
    "citations_total": 28,
    "citations_total_excl_self": 23,
    "citation_start": "2023-10"
  },
  {
    "id": "shaper",
    "title": "SHAPER: Can You Hear the Shape of a Jet?",
    "date": "2023-02-26",
    "authors": "Demba Ba, Akshunna S. Dogra, Rikab Gambhir, Abiy Tasissa, Jesse Thaler",
    "img": "assets/img/SHAPER.gif",
    "blurb": "Earth-Mover's Distance emerges as the natural metric for collider events; introduces the SHAPER framework for new IRC-safe shape observables.",
    "abstract": "",
    "tags": [
      "optimal-transport",
      "jets",
      "ml"
    ],
    "featured": true,
    "joke": false,
    "status": "refereed",
    "bibtex": "@article{Ba:2023hix,\n    author = \"Ba, Demba and Dogra, Akshunna S. and Gambhir, Rikab and Tasissa, Abiy and Thaler, Jesse\",\n    title = \"{SHAPER: can you hear the shape of a jet?}\",\n    eprint = \"2302.12266\",\n    archivePrefix = \"arXiv\",\n    primaryClass = \"hep-ph\",\n    reportNumber = \"MIT-CTP 5535\",\n    doi = \"10.1007/JHEP06(2023)195\",\n    journal = \"JHEP\",\n    volume = \"06\",\n    pages = \"195\",\n    year = \"2023\"\n}",
    "links": [
      {
        "text": "INSPIRE-HEP",
        "href": "https://inspirehep.net/literature?q=arxiv:2302.12266"
      },
      {
        "text": "arXiv 2302.12266",
        "href": "https://arxiv.org/abs/2302.12266"
      },
      {
        "text": "J. High Energ. Phys. 2023, 195",
        "href": "https://link.springer.com/article/10.1007/JHEP06(2023)195"
      },
      {
        "text": "GitHub",
        "href": "https://github.com/rikab/SHAPER"
      }
    ],
    "talks": [
      "the-shape-of-jets-2026-03-17",
      "the-shape-of-jets-2025-10-10",
      "the-shape-of-jets-2025-09-22",
      "the-shape-of-jets-2025-03-04",
      "an-iaifi-story-can-you-hear-the-shape-of-2023-05-16",
      "can-you-hear-the-shape-of-a-jet-2023-03-17",
      "can-you-hear-the-shape-of-a-jet-2022-11-04",
      "can-you-hear-the-shape-of-a-jet-2022-08-15",
      "can-you-hear-the-shape-of-a-jet-iaifi-ns-2022-08-11",
      "can-you-hear-the-shape-of-a-jet-2022-04-10"
    ],
    "citations": [
      {
        "month": "2023-02",
        "count": 1
      },
      {
        "month": "2023-05",
        "count": 2
      },
      {
        "month": "2023-06",
        "count": 3
      },
      {
        "month": "2023-09",
        "count": 4
      },
      {
        "month": "2024-01",
        "count": 6
      },
      {
        "month": "2024-03",
        "count": 7
      },
      {
        "month": "2024-08",
        "count": 8
      },
      {
        "month": "2024-10",
        "count": 9
      },
      {
        "month": "2025-01",
        "count": 11
      },
      {
        "month": "2025-03",
        "count": 13
      },
      {
        "month": "2025-04",
        "count": 14
      },
      {
        "month": "2025-05",
        "count": 16
      },
      {
        "month": "2025-06",
        "count": 17
      },
      {
        "month": "2025-07",
        "count": 19
      },
      {
        "month": "2025-11",
        "count": 21
      }
    ],
    "citations_excl_self": [
      {
        "month": "2023-02",
        "count": 1
      },
      {
        "month": "2023-06",
        "count": 2
      },
      {
        "month": "2023-09",
        "count": 3
      },
      {
        "month": "2024-01",
        "count": 5
      },
      {
        "month": "2024-08",
        "count": 6
      },
      {
        "month": "2025-01",
        "count": 8
      },
      {
        "month": "2025-03",
        "count": 9
      },
      {
        "month": "2025-04",
        "count": 10
      },
      {
        "month": "2025-05",
        "count": 11
      },
      {
        "month": "2025-06",
        "count": 12
      },
      {
        "month": "2025-07",
        "count": 14
      },
      {
        "month": "2025-11",
        "count": 16
      }
    ],
    "citations_total": 21,
    "citations_total_excl_self": 16,
    "citation_start": "2023-02"
  },
  {
    "id": "calibration-priors",
    "title": "Bias and Priors in Machine-Learning Calibrations for High-Energy Physics",
    "date": "2022-05-11",
    "authors": "Rikab Gambhir, Benjamin Nachman, Jesse Thaler",
    "img": "assets/img/Calibration_Priors.png",
    "blurb": "Demonstrates how simulation- and data-derived calibrations inherit sample-specific biases; shows Gaussian Ansatz mitigates prior dependence.",
    "abstract": "",
    "tags": [
      "ml",
      "calibration",
      "statistics"
    ],
    "featured": false,
    "joke": false,
    "status": "refereed",
    "bibtex": "@article{Gambhir:2022dut,\n    author = \"Gambhir, Rikab and Nachman, Benjamin and Thaler, Jesse\",\n    title = \"{Bias and priors in machine learning calibrations for high energy physics}\",\n    eprint = \"2205.05084\",\n    archivePrefix = \"arXiv\",\n    primaryClass = \"hep-ph\",\n    reportNumber = \"MIT-CTP 5432\",\n    doi = \"10.1103/PhysRevD.106.036011\",\n    journal = \"Phys. Rev. D\",\n    volume = \"106\",\n    number = \"3\",\n    pages = \"036011\",\n    year = \"2022\"\n}",
    "links": [
      {
        "text": "INSPIRE-HEP",
        "href": "https://inspirehep.net/literature?q=arxiv:2205.05084"
      },
      {
        "text": "arXiv 2205.05084",
        "href": "https://arxiv.org/abs/2205.05084"
      },
      {
        "text": "Phys. Rev. D 106, 036011",
        "href": "https://journals.aps.org/prd/abstract/10.1103/PhysRevD.106.036011"
      },
      {
        "text": "Notebook repo",
        "href": "https://github.com/hep-lbdl/calibrationpriors"
      }
    ],
    "talks": [],
    "citations": [
      {
        "month": "2022-05",
        "count": 1
      },
      {
        "month": "2023-10",
        "count": 2
      },
      {
        "month": "2023-12",
        "count": 3
      },
      {
        "month": "2024-01",
        "count": 5
      },
      {
        "month": "2024-02",
        "count": 6
      },
      {
        "month": "2024-04",
        "count": 8
      },
      {
        "month": "2025-05",
        "count": 11
      },
      {
        "month": "2025-08",
        "count": 12
      }
    ],
    "citations_excl_self": [
      {
        "month": "2022-05",
        "count": 0
      },
      {
        "month": "2023-12",
        "count": 1
      },
      {
        "month": "2024-01",
        "count": 3
      },
      {
        "month": "2024-04",
        "count": 4
      },
      {
        "month": "2025-08",
        "count": 5
      }
    ],
    "citations_total": 12,
    "citations_total_excl_self": 5,
    "citation_start": "2022-05"
  },
  {
    "id": "frequentist-way",
    "title": "Learning Uncertainties the Frequentist Way: Calibration and Correlation in High-Energy Physics",
    "date": "2022-05-09",
    "authors": "Rikab Gambhir, Benjamin Nachman, Jesse Thaler",
    "img": "assets/img/Freq_Way.png",
    "blurb": "Presents a likelihood-based inference framework with Gaussian uncertainty estimates and mutual-information diagnostics.",
    "abstract": "",
    "tags": [
      "ml",
      "calibration",
      "statistics"
    ],
    "featured": false,
    "joke": false,
    "status": "refereed",
    "bibtex": "@article{Gambhir:2022gua,\n    author = \"Gambhir, Rikab and Nachman, Benjamin and Thaler, Jesse\",\n    title = \"{Learning Uncertainties the Frequentist Way: Calibration and Correlation in High Energy Physics}\",\n    eprint = \"2205.03413\",\n    archivePrefix = \"arXiv\",\n    primaryClass = \"hep-ph\",\n    reportNumber = \"MIT-CTP 5431\",\n    doi = \"10.1103/PhysRevLett.129.082001\",\n    journal = \"Phys. Rev. Lett.\",\n    volume = \"129\",\n    number = \"8\",\n    pages = \"082001\",\n    year = \"2022\"\n}",
    "links": [
      {
        "text": "INSPIRE-HEP",
        "href": "https://inspirehep.net/literature?q=arxiv:2205.03413"
      },
      {
        "text": "arXiv 2205.03413",
        "href": "https://arxiv.org/abs/2205.03413"
      },
      {
        "text": "Phys. Rev. Lett. 129, 082001",
        "href": "https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.129.082001"
      },
      {
        "text": "GitHub",
        "href": "https://github.com/rikab/GaussianAnsatz/tree/main/JEC"
      }
    ],
    "talks": [
      "learning-uncertainties-the-frequentist-w-2022-12-03",
      "learning-uncertainties-the-frequentist-w-2022-11-22",
      "learning-uncertainties-the-frequentist-w-2022-09-13",
      "learning-uncertainties-the-frequentist-w-2021-07-07"
    ],
    "citations": [
      {
        "month": "2022-05",
        "count": 2
      },
      {
        "month": "2022-08",
        "count": 3
      },
      {
        "month": "2023-09",
        "count": 4
      },
      {
        "month": "2024-01",
        "count": 5
      },
      {
        "month": "2024-02",
        "count": 6
      },
      {
        "month": "2024-04",
        "count": 8
      },
      {
        "month": "2024-12",
        "count": 9
      },
      {
        "month": "2025-01",
        "count": 10
      },
      {
        "month": "2025-05",
        "count": 12
      },
      {
        "month": "2025-08",
        "count": 14
      }
    ],
    "citations_excl_self": [
      {
        "month": "2022-05",
        "count": 1
      },
      {
        "month": "2023-09",
        "count": 2
      },
      {
        "month": "2024-01",
        "count": 3
      },
      {
        "month": "2024-04",
        "count": 4
      },
      {
        "month": "2024-12",
        "count": 5
      },
      {
        "month": "2025-01",
        "count": 6
      },
      {
        "month": "2025-08",
        "count": 8
      }
    ],
    "citations_total": 14,
    "citations_total_excl_self": 8,
    "citation_start": "2022-05"
  },
  {
    "id": "vlq",
    "title": "Search for bottom-type vector-like-quark pair production in a fully hadronic final state at √s = 13 TeV",
    "date": "2020-12-07",
    "authors": "CMS Collaboration",
    "img": "assets/img/exclusion.png",
    "blurb": "Sets the then-tightest limits on VLQ→hadronic decays using the full Run-2 CMS data set.",
    "abstract": "",
    "tags": [
      "bsm",
      "cms"
    ],
    "featured": false,
    "joke": false,
    "status": "refereed",
    "bibtex": "@article{CMS:2020ttz,\n    author = \"Sirunyan, Albert M and others\",\n    collaboration = \"CMS\",\n    title = \"{A search for bottom-type, vector-like quark pair production in a fully hadronic final state in proton-proton collisions at $\\sqrt{s} =$ 13 TeV}\",\n    eprint = \"2008.09835\",\n    archivePrefix = \"arXiv\",\n    primaryClass = \"hep-ex\",\n    reportNumber = \"CMS-B2G-19-005, CERN-EP-2020-154\",\n    doi = \"10.1103/PhysRevD.102.112004\",\n    journal = \"Phys. Rev. D\",\n    volume = \"102\",\n    pages = \"112004\",\n    year = \"2020\"\n}",
    "links": [
      {
        "text": "INSPIRE-HEP",
        "href": "https://inspirehep.net/literature?q=arxiv:2008.09835"
      },
      {
        "text": "arXiv 2008.09835",
        "href": "https://arxiv.org/abs/2008.09835"
      },
      {
        "text": "Phys. Rev. D 102, IPhT, Saclay, France112004",
        "href": "https://journals.aps.org/prd/abstract/10.1103/PhysRevD.102.112004"
      }
    ],
    "talks": [
      "a-search-for-fully-hadronic-final-state--2020-04-19",
      "a-search-for-fully-hadronic-final-state--2019-07-29"
    ],
    "citations": [
      {
        "month": "2020-12",
        "count": 0
      },
      {
        "month": "2021-01",
        "count": 3
      },
      {
        "month": "2021-03",
        "count": 4
      },
      {
        "month": "2021-04",
        "count": 5
      },
      {
        "month": "2021-05",
        "count": 11
      },
      {
        "month": "2021-06",
        "count": 14
      },
      {
        "month": "2021-07",
        "count": 16
      },
      {
        "month": "2021-09",
        "count": 18
      },
      {
        "month": "2021-11",
        "count": 19
      },
      {
        "month": "2021-12",
        "count": 21
      },
      {
        "month": "2022-01",
        "count": 26
      },
      {
        "month": "2022-02",
        "count": 29
      },
      {
        "month": "2022-03",
        "count": 32
      },
      {
        "month": "2022-04",
        "count": 34
      },
      {
        "month": "2022-05",
        "count": 36
      },
      {
        "month": "2022-06",
        "count": 37
      },
      {
        "month": "2022-07",
        "count": 39
      },
      {
        "month": "2022-08",
        "count": 42
      },
      {
        "month": "2022-09",
        "count": 44
      },
      {
        "month": "2022-10",
        "count": 45
      },
      {
        "month": "2022-11",
        "count": 49
      },
      {
        "month": "2022-12",
        "count": 52
      },
      {
        "month": "2023-01",
        "count": 55
      },
      {
        "month": "2023-03",
        "count": 58
      },
      {
        "month": "2023-04",
        "count": 59
      },
      {
        "month": "2023-06",
        "count": 60
      },
      {
        "month": "2023-08",
        "count": 62
      },
      {
        "month": "2023-09",
        "count": 63
      },
      {
        "month": "2023-10",
        "count": 64
      },
      {
        "month": "2023-11",
        "count": 65
      },
      {
        "month": "2023-12",
        "count": 66
      },
      {
        "month": "2024-01",
        "count": 70
      },
      {
        "month": "2024-02",
        "count": 72
      },
      {
        "month": "2024-05",
        "count": 74
      },
      {
        "month": "2024-06",
        "count": 75
      },
      {
        "month": "2024-08",
        "count": 77
      },
      {
        "month": "2024-09",
        "count": 78
      },
      {
        "month": "2024-11",
        "count": 79
      },
      {
        "month": "2024-12",
        "count": 81
      },
      {
        "month": "2025-02",
        "count": 82
      },
      {
        "month": "2025-05",
        "count": 83
      },
      {
        "month": "2025-06",
        "count": 84
      },
      {
        "month": "2025-07",
        "count": 85
      },
      {
        "month": "2025-10",
        "count": 86
      },
      {
        "month": "2025-12",
        "count": 87
      },
      {
        "month": "2026-04",
        "count": 88
      },
      {
        "month": "2026-05",
        "count": 89
      }
    ],
    "citations_excl_self": [
      {
        "month": "2020-12",
        "count": 0
      },
      {
        "month": "2021-01",
        "count": 3
      },
      {
        "month": "2021-03",
        "count": 4
      },
      {
        "month": "2021-04",
        "count": 5
      },
      {
        "month": "2021-05",
        "count": 11
      },
      {
        "month": "2021-06",
        "count": 14
      },
      {
        "month": "2021-07",
        "count": 16
      },
      {
        "month": "2021-09",
        "count": 18
      },
      {
        "month": "2021-11",
        "count": 19
      },
      {
        "month": "2021-12",
        "count": 21
      },
      {
        "month": "2022-01",
        "count": 26
      },
      {
        "month": "2022-02",
        "count": 29
      },
      {
        "month": "2022-03",
        "count": 32
      },
      {
        "month": "2022-04",
        "count": 34
      },
      {
        "month": "2022-05",
        "count": 36
      },
      {
        "month": "2022-06",
        "count": 37
      },
      {
        "month": "2022-07",
        "count": 39
      },
      {
        "month": "2022-08",
        "count": 42
      },
      {
        "month": "2022-09",
        "count": 44
      },
      {
        "month": "2022-10",
        "count": 45
      },
      {
        "month": "2022-11",
        "count": 49
      },
      {
        "month": "2022-12",
        "count": 52
      },
      {
        "month": "2023-01",
        "count": 55
      },
      {
        "month": "2023-03",
        "count": 58
      },
      {
        "month": "2023-04",
        "count": 59
      },
      {
        "month": "2023-06",
        "count": 60
      },
      {
        "month": "2023-08",
        "count": 62
      },
      {
        "month": "2023-09",
        "count": 63
      },
      {
        "month": "2023-10",
        "count": 64
      },
      {
        "month": "2023-11",
        "count": 65
      },
      {
        "month": "2023-12",
        "count": 66
      },
      {
        "month": "2024-01",
        "count": 70
      },
      {
        "month": "2024-02",
        "count": 72
      },
      {
        "month": "2024-05",
        "count": 74
      },
      {
        "month": "2024-06",
        "count": 75
      },
      {
        "month": "2024-08",
        "count": 77
      },
      {
        "month": "2024-09",
        "count": 78
      },
      {
        "month": "2024-11",
        "count": 79
      },
      {
        "month": "2024-12",
        "count": 81
      },
      {
        "month": "2025-02",
        "count": 82
      },
      {
        "month": "2025-05",
        "count": 83
      },
      {
        "month": "2025-06",
        "count": 84
      },
      {
        "month": "2025-07",
        "count": 85
      },
      {
        "month": "2025-10",
        "count": 86
      },
      {
        "month": "2025-12",
        "count": 87
      },
      {
        "month": "2026-04",
        "count": 88
      },
      {
        "month": "2026-05",
        "count": 89
      }
    ],
    "citations_total": 89,
    "citations_total_excl_self": 89,
    "citation_start": "2020-12"
  }
];

export const talk_data = [
  {
    "id": "resummed-distribution-functions-making-p-2026-04-30",
    "title": "Resummed Distribution Functions: Making Perturbation Theory Positive and Normalized",
    "where": "Fermilab Theory Seminar",
    "date": "2026-04-30",
    "category": "invited",
    "topic": "",
    "slides": "./assets/talks/[Fermilab 2026] RDFs.pdf",
    "video": null,
    "featured": true,
    "paper": "rdf",
    "abstract": ""
  },
  {
    "id": "interpreting-interpretability-and-explai-2026-04-27",
    "title": "Interpreting ``Interpretability'' and Explaining ``Explainability'' in ML and Physics",
    "where": "HEP Lunch Seminar, UChicago",
    "date": "2026-04-27",
    "category": "invited",
    "topic": "",
    "slides": "./assets/talks/[UChicago 2026] Interpreting “Interpretability”.pdf",
    "video": null,
    "featured": true,
    "paper": null,
    "abstract": ""
  },
  {
    "id": "interpreting-interpretability-and-explai-2026-04-16",
    "title": "Interpreting ``Interpretability'' and Explaining ``Explainability'' in ML and Physics",
    "where": "IAIFI Lunch Seminar, MIT",
    "date": "2026-04-16",
    "category": "invited",
    "topic": "",
    "slides": "./assets/talks/[IAIFI 2026] Interpreting “Interpretability”.pdf",
    "video": null,
    "featured": true,
    "paper": null,
    "abstract": ""
  },
  {
    "id": "resummed-distribution-functions-making-p-2026-04-02",
    "title": "Resummed Distribution Functions: Making Perturbation Theory Positive and Normalized",
    "where": "Institut de Physique Théorique (IPhT)",
    "date": "2026-04-02",
    "category": "invited",
    "topic": "",
    "slides": "./assets/talks/[IPHT 2026] RDFs.pdf",
    "video": null,
    "featured": true,
    "paper": "rdf",
    "abstract": ""
  },
  {
    "id": "the-shape-of-jets-2026-03-17",
    "title": "The Shape of Jets",
    "where": "KITP Particle Theory Initiative",
    "date": "2026-03-17",
    "category": "invited",
    "topic": "",
    "slides": "./assets/talks/[KITP 2026] The Shape of Jets.pdf",
    "video": "https://online.kitp.ucsb.edu/online/quarkgluon26/gambhir/",
    "featured": true,
    "paper": "shaper",
    "abstract": ""
  },
  {
    "id": "hd-sense-an-efficient-method-for-ranking-2026-03-09",
    "title": "HD Sense: An efficient method for ranking observable sensitivity",
    "where": "LPCC MCWG Tuning Forum",
    "date": "2026-03-09",
    "category": "contributed",
    "topic": "HDSense",
    "slides": "./assets/talks/[LPCC 2026] HD Sense.pdf",
    "video": "https://indico.cern.ch/event/1648114/",
    "featured": false,
    "paper": "hdsense",
    "abstract": ""
  },
  {
    "id": "interpreting-interpretability-and-explai-2026-02-17",
    "title": "Interpreting ``Interpretability'' and Explaining ``Explainability'' in ML and Physics",
    "where": "VERaiPHY, Nikhef",
    "date": "2026-02-17",
    "category": "contributed",
    "topic": "",
    "slides": "./assets/talks/[NIKHEF 2026] Interpreting “Interpretability”.pdf",
    "video": "https://indico.cern.ch/event/1617006/contributions/6877944/",
    "featured": false,
    "paper": null,
    "abstract": ""
  },
  {
    "id": "interpreting-interpretability-in-ml-and--2025-11-21",
    "title": "Interpreting ``Interpretability'' in ML and Physics",
    "where": "",
    "date": "2025-11-21",
    "category": "lectures",
    "topic": "",
    "slides": null,
    "video": null,
    "featured": false,
    "paper": null,
    "abstract": ""
  },
  {
    "id": "the-shape-of-jets-2025-10-10",
    "title": "The Shape of Jets",
    "where": "Alabama HEP/Astro Seminar, University of Alabama (AL)",
    "date": "2025-10-10",
    "category": "invited",
    "topic": "",
    "slides": "./assets/talks/The Shape of Jets [Alabama 2025].pdf",
    "video": "https://physics.ua.edu/2025/10/14/high-energy-and-particle-physics-seminar/",
    "featured": true,
    "paper": "shaper",
    "abstract": ""
  },
  {
    "id": "the-shape-of-jets-2025-09-22",
    "title": "The Shape of Jets",
    "where": "Cincinnati HEP/Astro Seminar, University of Cincinnati (OH)",
    "date": "2025-09-22",
    "category": "invited",
    "topic": "",
    "slides": "./assets/talks/The Shape of Jets [Cincy 2025].pdf",
    "video": null,
    "featured": true,
    "paper": "shaper",
    "abstract": ""
  },
  {
    "id": "the-pareto-frontier-of-resilient-jet-tag-2025-08-21",
    "title": "The Pareto Frontier of Resilient Jet Tagging",
    "where": "ML4Jets 2025, Caltech (CA)",
    "date": "2025-08-21",
    "category": "contributed",
    "topic": "Pareto Frontier",
    "slides": null,
    "video": null,
    "featured": false,
    "paper": "pareto",
    "abstract": ""
  },
  {
    "id": "re-normalizing-flows-taming-logs-and-per-2025-07-30",
    "title": "Re-Normalizing Flows: Taming Logs and Perturbation Theory in QCD",
    "where": "BOOST 2025, Brown University (RI)",
    "date": "2025-07-30",
    "category": "contributed",
    "topic": "Resummed Distribution Functions",
    "slides": null,
    "video": null,
    "featured": false,
    "paper": "rdf",
    "abstract": ""
  },
  {
    "id": "machine-learning-tutorials-2025-06-21",
    "title": "Machine Learning Tutorials",
    "where": "",
    "date": "2025-06-21",
    "category": "lectures",
    "topic": "",
    "slides": null,
    "video": null,
    "featured": false,
    "paper": null,
    "abstract": ""
  },
  {
    "id": "likelihood-based-reweighting-for-improve-2025-06-18",
    "title": "Likelihood-based Reweighting for Improved sensitivity in Anomaly Detection",
    "where": "AD4HEP 2025, Columbia (NY)",
    "date": "2025-06-18",
    "category": "contributed",
    "topic": "",
    "slides": null,
    "video": null,
    "featured": false,
    "paper": "upsilons",
    "abstract": ""
  },
  {
    "id": "moments-of-clarity-in-machine-learning-f-2025-06-11",
    "title": "Moments of Clarity in Machine Learning for Jet Physics",
    "where": "Harvard, Cambridge (MA)",
    "date": "2025-06-11",
    "category": "invited",
    "topic": "",
    "slides": "./assets/talks/Talk [Harvard 2025].pdf",
    "video": null,
    "featured": true,
    "paper": "moments",
    "abstract": ""
  },
  {
    "id": "isolating-unisolated-upsilons-with-anoma-2025-05-20",
    "title": "Isolating Unisolated Upsilons with Anomaly Detection in CMS Open Data",
    "where": "Pheno 2025, Univ. Pittsburgh (PA)",
    "date": "2025-05-20",
    "category": "contributed",
    "topic": "",
    "slides": null,
    "video": null,
    "featured": false,
    "paper": "upsilons",
    "abstract": ""
  },
  {
    "id": "moments-of-clarity-in-machine-learning-f-2025-03-12",
    "title": "Moments of Clarity in Machine Learning for Jet Physics",
    "where": "Yale AI/Physics Seminar, New Haven (CT)",
    "date": "2025-03-12",
    "category": "invited",
    "topic": "",
    "slides": "./assets/talks/Moments of Clarity [Yale 2025].pdf",
    "video": null,
    "featured": true,
    "paper": "moments",
    "abstract": ""
  },
  {
    "id": "the-shape-of-jets-2025-03-04",
    "title": "The Shape of Jets",
    "where": "LBNL AI Seminar, (Virtual)",
    "date": "2025-03-04",
    "category": "invited",
    "topic": "",
    "slides": "./assets/talks/The Shape of Jets [LBNL 2025].pdf",
    "video": null,
    "featured": true,
    "paper": "shaper",
    "abstract": ""
  },
  {
    "id": "moments-of-clarity-in-machine-learning-f-2024-12-18",
    "title": "Moments of Clarity in Machine Learning for Jet Physics",
    "where": "Brown Physics Seminar, Providence (RI)",
    "date": "2024-12-18",
    "category": "invited",
    "topic": "",
    "slides": "./assets/talks/Moments of Clarity [Brown 2024].pdf",
    "video": null,
    "featured": true,
    "paper": "moments",
    "abstract": ""
  },
  {
    "id": "re-normalizing-flows-taming-logs-and-per-2024-11-05",
    "title": "Re-Normalizing Flows: Taming Logs and Perturbation Theory in QCD",
    "where": "ML4Jets 2024, LPNHE Paris (France)",
    "date": "2024-11-05",
    "category": "contributed",
    "topic": "Resummed Distribution Functions",
    "slides": null,
    "video": null,
    "featured": false,
    "paper": "rdf",
    "abstract": ""
  },
  {
    "id": "moments-of-clarity-in-machine-learning-f-2024-10-18",
    "title": "Moments of Clarity in Machine Learning for Jet Physics",
    "where": "Rutgers Journal Club, New Brunswick (NJ)",
    "date": "2024-10-18",
    "category": "invited",
    "topic": "",
    "slides": "./assets/talks/Moments of Clarity [Rutgers 2024].pdf",
    "video": null,
    "featured": true,
    "paper": "moments",
    "abstract": ""
  },
  {
    "id": "moments-of-clarity-in-machine-learning-f-2024-10-11",
    "title": "Moments of Clarity in Machine Learning for Jet Physics",
    "where": "UIUC Physics Seminar, Urbana-Champaign (IL)",
    "date": "2024-10-11",
    "category": "invited",
    "topic": "",
    "slides": "./assets/talks/Moments of Clarity [UIUC 2024].pdf",
    "video": null,
    "featured": true,
    "paper": "moments",
    "abstract": ""
  },
  {
    "id": "moments-of-clarity-in-jet-physics-with-m-2024-09-24",
    "title": "Moments of Clarity in Jet Physics with Machine Learning",
    "where": "IAIFI Journal Club, MIT",
    "date": "2024-09-24",
    "category": "contributed",
    "topic": "",
    "slides": null,
    "video": null,
    "featured": false,
    "paper": "moments",
    "abstract": ""
  },
  {
    "id": "specter-efficient-evaluation-of-the-spec-2024-08-15",
    "title": "SPECTER: Efficient Evaluation of the Spectral EMD",
    "where": "IAIFI Workshop, MIT Media Lab",
    "date": "2024-08-15",
    "category": "contributed",
    "topic": "SPECTER – Spectral EMD",
    "slides": "./assets/talks/(IAIFI 2024) SPECTER.pdf",
    "video": "https://iaifi.org/summer-workshop",
    "featured": true,
    "paper": "specter",
    "abstract": ""
  },
  {
    "id": "specter-efficient-evaluation-of-the-spec-2024-07-31",
    "title": "SPECTER: Efficient Evaluation of the Spectral EMD",
    "where": "BOOST 2024, Genova (Italy)",
    "date": "2024-07-31",
    "category": "contributed",
    "topic": "SPECTER – Spectral EMD",
    "slides": "./assets/talks/(BOOST 2024) SPECTER.pdf",
    "video": "https://agenda.infn.it/event/37093/contributions/234299/",
    "featured": false,
    "paper": "specter",
    "abstract": ""
  },
  {
    "id": "moments-of-clarity-in-machine-learning-f-2024-05-28",
    "title": "Moments of Clarity in Machine Learning for Jet Physics",
    "where": "SLAC AI Seminar (virtual)",
    "date": "2024-05-28",
    "category": "invited",
    "topic": "",
    "slides": "./assets/talks/(SLAC 2024) ML And Colliders.pdf",
    "video": "https://stanford.zoom.us/rec/share/oJLuBcLOiD_OrJjNc7C01kq09xQYhaK3CYpn0VzyXFCsdt1xMp24ZwBSzMcIoXyh.BKP0GP6--Qu0LthP",
    "featured": true,
    "paper": "moments",
    "abstract": ""
  },
  {
    "id": "the-new-physics-case-for-muon-beam-dump--2024-05-16",
    "title": "The New Physics Case for Muon Beam Dump Experiments",
    "where": "DPF-Pheno 2024, Univ. Pittsburgh",
    "date": "2024-05-16",
    "category": "contributed",
    "topic": "Muon Beam Dumps",
    "slides": "./assets/talks/(Pheno 2024) Muon Beam Dump.pdf",
    "video": "https://indico.cern.ch/event/1358339/contributions/5899388/",
    "featured": false,
    "paper": "muon-beam-dump",
    "abstract": ""
  },
  {
    "id": "the-new-physics-case-for-muon-beam-dump--2024-03-19",
    "title": "The New Physics Case for Muon Beam-Dump Experiments",
    "where": "MIT CTP Graduate Seminar",
    "date": "2024-03-19",
    "category": "contributed",
    "topic": "Muon Beam Dumps",
    "slides": "./assets/talks/(Grad Seminar 2024) Muon Beam Dump-1.pdf",
    "video": null,
    "featured": true,
    "paper": "muon-beam-dump",
    "abstract": ""
  },
  {
    "id": "specter-efficient-evaluation-of-the-spec-2023-11-08",
    "title": "SPECTER: Efficient Evaluation of the Spectral EMD",
    "where": "ML4Jets 2023, DESY Hamburg",
    "date": "2023-11-08",
    "category": "contributed",
    "topic": "SPECTER – Spectral EMD",
    "slides": "./assets/talks/(ML4Jets 2023) SPECTER-2.pdf",
    "video": "https://indico.cern.ch/event/1253794/contributions/5588542/",
    "featured": false,
    "paper": "specter",
    "abstract": ""
  },
  {
    "id": "moment-pooling-performance-interpretabil-2023-08-02",
    "title": "Moment Pooling: Performance & Interpretability via Physics-Inspired Products",
    "where": "BOOST 2023, LBNL Berkeley",
    "date": "2023-08-02",
    "category": "contributed",
    "topic": "Moment Pooling",
    "slides": "./assets/talks/(BOOST 2023) Moment Pooling.pdf",
    "video": "https://indico.physics.lbl.gov/event/975/contributions/8280/",
    "featured": true,
    "paper": "moments",
    "abstract": ""
  },
  {
    "id": "how-do-i-take-my-cup-of-cms-open-data-2023-07-11",
    "title": "How Do I Take My Cup of CMS Open Data?",
    "where": "CMS Open-Data Workshop 2023, Fermilab (IL)",
    "date": "2023-07-11",
    "category": "invited",
    "topic": "",
    "slides": "./assets/talks/(Fermilab 2023) CMS Open Data-2.pdf",
    "video": "https://indico.fnal.gov/event/58914/timetable/",
    "featured": true,
    "paper": null,
    "abstract": ""
  },
  {
    "id": "an-iaifi-story-can-you-hear-the-shape-of-2023-05-16",
    "title": "An IAIFI Story – Can You Hear the Shape of a Jet?",
    "where": "IAIFI Engineering Advisory Board",
    "date": "2023-05-16",
    "category": "contributed",
    "topic": "Can You Hear the Shape of a Jet?",
    "slides": "./assets/talks/(IAIFI 2023) Can you hear the shape of a jet_.pdf",
    "video": null,
    "featured": false,
    "paper": "shaper",
    "abstract": ""
  },
  {
    "id": "moment-pooling-performance-interpretabil-2023-04-17",
    "title": "Moment Pooling: Performance & Interpretability via Physics-Inspired Products",
    "where": "APS April Meeting 2023, Minneapolis",
    "date": "2023-04-17",
    "category": "contributed",
    "topic": "Moment Pooling",
    "slides": "./assets/talks/(APS 2023) Moment Pooling-4.pdf",
    "video": "https://meetings.aps.org/Meeting/APR23/Session/M11.6",
    "featured": false,
    "paper": "moments",
    "abstract": ""
  },
  {
    "id": "can-you-hear-the-shape-of-a-jet-2023-03-17",
    "title": "Can You Hear the Shape of a Jet?",
    "where": "MIT CTP Graduate Seminar",
    "date": "2023-03-17",
    "category": "contributed",
    "topic": "Can You Hear the Shape of a Jet?",
    "slides": "./assets/talks/(Grad Seminar 2023) Can you hear the shape of a jet .pdf",
    "video": null,
    "featured": true,
    "paper": "shaper",
    "abstract": ""
  },
  {
    "id": "learning-uncertainties-the-frequentist-w-2022-12-03",
    "title": "Learning Uncertainties the Frequentist Way: Calibration and Correlation in High Energy Physics",
    "where": "ML & Physical Sciences @ NeurIPS 2022",
    "date": "2022-12-03",
    "category": "contributed",
    "topic": "Frequentist Way – Calibration & Correlation",
    "slides": "./assets/talks/frequentist_way_poster.png",
    "video": "https://neurips.cc/virtual/2022/event/56849",
    "featured": false,
    "paper": "frequentist-way",
    "abstract": ""
  },
  {
    "id": "learning-uncertainties-the-frequentist-w-2022-11-22",
    "title": "Learning Uncertainties the Frequentist Way: Calibration and Correlation in High Energy Physics",
    "where": "ATLAS Jet/Etmiss Seminar, CERN (virtual)",
    "date": "2022-11-22",
    "category": "invited",
    "topic": "",
    "slides": "./assets/talks/(ATLAS) Frequentist Way.pdf",
    "video": "https://indico.cern.ch/event/1223571/",
    "featured": true,
    "paper": "frequentist-way",
    "abstract": ""
  },
  {
    "id": "can-you-hear-the-shape-of-a-jet-2022-11-04",
    "title": "Can You Hear the Shape of a Jet?",
    "where": "ML4Jets 2022, Rutgers University",
    "date": "2022-11-04",
    "category": "contributed",
    "topic": "Can You Hear the Shape of a Jet?",
    "slides": "./assets/talks/(ML4Jets 2022) Can you hear the shape of a jet .pdf",
    "video": "https://indico.cern.ch/event/1159913/contributions/5062759/",
    "featured": false,
    "paper": "shaper",
    "abstract": ""
  },
  {
    "id": "learning-uncertainties-the-frequentist-w-2022-09-13",
    "title": "Learning Uncertainties the Frequentist Way: Calibration and Correlation in High Energy Physics",
    "where": "Astro/Particle-ML Seminar, UCI (virtual)",
    "date": "2022-09-13",
    "category": "invited",
    "topic": "",
    "slides": "./assets/talks/(UCI) Frequentist Way-1-1.pdf",
    "video": null,
    "featured": false,
    "paper": "frequentist-way",
    "abstract": ""
  },
  {
    "id": "can-you-hear-the-shape-of-a-jet-2022-08-15",
    "title": "Can You Hear the Shape of a Jet?",
    "where": "BOOST 2022, Univ. Hamburg",
    "date": "2022-08-15",
    "category": "contributed",
    "topic": "Can You Hear the Shape of a Jet?",
    "slides": "./assets/talks/(BOOST 2022) Can you hear the shape of a jet -2.pdf",
    "video": "https://indico.cern.ch/event/1144064/contributions/4940343/",
    "featured": false,
    "paper": "shaper",
    "abstract": ""
  },
  {
    "id": "can-you-hear-the-shape-of-a-jet-iaifi-ns-2022-08-11",
    "title": "Can You Hear the Shape of a Jet? – IAIFI/NSF Review",
    "where": "MIT, Cambridge (MA)",
    "date": "2022-08-11",
    "category": "contributed",
    "topic": "Can You Hear the Shape of a Jet?",
    "slides": "./assets/talks/IAIFI Story.pdf",
    "video": null,
    "featured": false,
    "paper": "shaper",
    "abstract": ""
  },
  {
    "id": "can-you-hear-the-shape-of-a-jet-2022-04-10",
    "title": "Can You Hear the Shape of a Jet?",
    "where": "APS April Meeting 2022, New York City",
    "date": "2022-04-10",
    "category": "contributed",
    "topic": "Can You Hear the Shape of a Jet?",
    "slides": "./assets/talks/can_you_hear_the_shape_of_a_jet.pdf",
    "video": "https://meetings.aps.org/Meeting/APR22/Session/K08.7",
    "featured": false,
    "paper": "shaper",
    "abstract": ""
  },
  {
    "id": "learning-uncertainties-the-frequentist-w-2021-07-07",
    "title": "Learning Uncertainties the Frequentist Way: Calibration and Correlation in High Energy Physics",
    "where": "ML4Jets 2021, Univ. Heidelberg (virtual)",
    "date": "2021-07-07",
    "category": "contributed",
    "topic": "Frequentist Way – Calibration & Correlation",
    "slides": "./assets/talks/Calibration and Correlation ML4Jets.pdf",
    "video": "https://indico.cern.ch/event/980214/contributions/4413598/",
    "featured": false,
    "paper": "frequentist-way",
    "abstract": ""
  },
  {
    "id": "a-search-for-fully-hadronic-final-state--2020-04-19",
    "title": "A Search for Fully Hadronic Final State Vector-Like Quark Pair Production in 13 TeV pp Collisions using CMS Data",
    "where": "",
    "date": "2020-04-19",
    "category": "contributed",
    "topic": "",
    "slides": null,
    "video": null,
    "featured": false,
    "paper": "vlq",
    "abstract": ""
  },
  {
    "id": "a-search-for-fully-hadronic-final-state--2019-07-29",
    "title": "A Search for Fully Hadronic Final State Vector-Like Quark Pair Production in 13 TeV pp Collisions using CMS Data",
    "where": "",
    "date": "2019-07-29",
    "category": "contributed",
    "topic": "",
    "slides": null,
    "video": null,
    "featured": false,
    "paper": "vlq",
    "abstract": ""
  },
  {
    "id": "how-can-we-model-insect-flight-quickly-a-2017-08-04",
    "title": "How Can We Model Insect Flight Quickly and Accurately?",
    "where": "",
    "date": "2017-08-04",
    "category": "contributed",
    "topic": "",
    "slides": null,
    "video": null,
    "featured": false,
    "paper": null,
    "abstract": ""
  }
];

export const software_data = [
  {
    "name": "SPECTER",
    "role": "Primary developer",
    "install": "pip install specterpy",
    "github": "https://github.com/rikab/SPECTER",
    "homepage": "",
    "paper": "specter",
    "blurb": "Framework for defining, building, and efficiently evaluating spectral shape observables for collider physics."
  },
  {
    "name": "SHAPER",
    "role": "Primary developer",
    "install": "pip install pyshaper",
    "github": "https://github.com/rikab/SHAPER",
    "homepage": "",
    "paper": "shaper",
    "blurb": "Shape Hunting Algorithm using Parameterized Energy Reconstruction — a framework for defining, building, and evaluating generalized shape observables."
  },
  {
    "name": "GaussianAnsatz",
    "role": "Primary developer",
    "install": "pip install GaussianAnsatz",
    "github": "https://github.com/rikab/GaussianAnsatz",
    "homepage": "",
    "paper": "frequentist-way",
    "blurb": "Machine-learning framework for frequentist inference, complete with local uncertainty estimation."
  },
  {
    "name": "ParticleLoader",
    "role": "Primary developer",
    "install": "",
    "github": "https://github.com/rikab/ParticleLoader",
    "homepage": "",
    "paper": null,
    "blurb": "Library for in-line downloading of standardized particle-physics datasets. Still in development; partial use possible."
  },
  {
    "name": "Energyflow",
    "role": "Maintainer",
    "install": "pip install energyflow",
    "github": "https://github.com/thaler-lab/EnergyFlow",
    "homepage": "https://energyflow.network",
    "paper": null,
    "blurb": "Established library of jet-physics tools developed before 2020. Current package maintainer."
  }
];

export const author_citations = [
  {
    "month": "2020-01",
    "total": 0,
    "excl_self": 0
  },
  {
    "month": "2021-01",
    "total": 3,
    "excl_self": 3
  },
  {
    "month": "2021-03",
    "total": 4,
    "excl_self": 4
  },
  {
    "month": "2021-04",
    "total": 5,
    "excl_self": 5
  },
  {
    "month": "2021-05",
    "total": 11,
    "excl_self": 11
  },
  {
    "month": "2021-06",
    "total": 14,
    "excl_self": 14
  },
  {
    "month": "2021-07",
    "total": 16,
    "excl_self": 16
  },
  {
    "month": "2021-09",
    "total": 18,
    "excl_self": 18
  },
  {
    "month": "2021-11",
    "total": 19,
    "excl_self": 19
  },
  {
    "month": "2021-12",
    "total": 21,
    "excl_self": 21
  },
  {
    "month": "2022-01",
    "total": 26,
    "excl_self": 26
  },
  {
    "month": "2022-02",
    "total": 29,
    "excl_self": 29
  },
  {
    "month": "2022-03",
    "total": 32,
    "excl_self": 32
  },
  {
    "month": "2022-04",
    "total": 34,
    "excl_self": 34
  },
  {
    "month": "2022-05",
    "total": 39,
    "excl_self": 37
  },
  {
    "month": "2022-06",
    "total": 40,
    "excl_self": 38
  },
  {
    "month": "2022-07",
    "total": 42,
    "excl_self": 40
  },
  {
    "month": "2022-08",
    "total": 46,
    "excl_self": 43
  },
  {
    "month": "2022-09",
    "total": 48,
    "excl_self": 45
  },
  {
    "month": "2022-10",
    "total": 49,
    "excl_self": 46
  },
  {
    "month": "2022-11",
    "total": 53,
    "excl_self": 50
  },
  {
    "month": "2022-12",
    "total": 56,
    "excl_self": 53
  },
  {
    "month": "2023-01",
    "total": 59,
    "excl_self": 56
  },
  {
    "month": "2023-02",
    "total": 60,
    "excl_self": 57
  },
  {
    "month": "2023-03",
    "total": 63,
    "excl_self": 60
  },
  {
    "month": "2023-04",
    "total": 64,
    "excl_self": 61
  },
  {
    "month": "2023-05",
    "total": 65,
    "excl_self": 61
  },
  {
    "month": "2023-06",
    "total": 67,
    "excl_self": 63
  },
  {
    "month": "2023-08",
    "total": 69,
    "excl_self": 65
  },
  {
    "month": "2023-09",
    "total": 72,
    "excl_self": 68
  },
  {
    "month": "2023-10",
    "total": 74,
    "excl_self": 69
  },
  {
    "month": "2023-11",
    "total": 76,
    "excl_self": 70
  },
  {
    "month": "2023-12",
    "total": 79,
    "excl_self": 73
  },
  {
    "month": "2024-01",
    "total": 88,
    "excl_self": 82
  },
  {
    "month": "2024-02",
    "total": 92,
    "excl_self": 84
  },
  {
    "month": "2024-03",
    "total": 94,
    "excl_self": 85
  },
  {
    "month": "2024-04",
    "total": 100,
    "excl_self": 88
  },
  {
    "month": "2024-05",
    "total": 103,
    "excl_self": 91
  },
  {
    "month": "2024-06",
    "total": 105,
    "excl_self": 93
  },
  {
    "month": "2024-07",
    "total": 107,
    "excl_self": 94
  },
  {
    "month": "2024-08",
    "total": 110,
    "excl_self": 97
  },
  {
    "month": "2024-09",
    "total": 113,
    "excl_self": 100
  },
  {
    "month": "2024-10",
    "total": 117,
    "excl_self": 103
  },
  {
    "month": "2024-11",
    "total": 118,
    "excl_self": 104
  },
  {
    "month": "2024-12",
    "total": 124,
    "excl_self": 110
  },
  {
    "month": "2025-01",
    "total": 131,
    "excl_self": 116
  },
  {
    "month": "2025-02",
    "total": 136,
    "excl_self": 121
  },
  {
    "month": "2025-03",
    "total": 142,
    "excl_self": 122
  },
  {
    "month": "2025-04",
    "total": 147,
    "excl_self": 125
  },
  {
    "month": "2025-05",
    "total": 162,
    "excl_self": 128
  },
  {
    "month": "2025-06",
    "total": 167,
    "excl_self": 133
  },
  {
    "month": "2025-07",
    "total": 172,
    "excl_self": 137
  },
  {
    "month": "2025-08",
    "total": 175,
    "excl_self": 140
  },
  {
    "month": "2025-09",
    "total": 179,
    "excl_self": 144
  },
  {
    "month": "2025-10",
    "total": 187,
    "excl_self": 151
  },
  {
    "month": "2025-11",
    "total": 192,
    "excl_self": 156
  },
  {
    "month": "2025-12",
    "total": 200,
    "excl_self": 161
  },
  {
    "month": "2026-01",
    "total": 202,
    "excl_self": 162
  },
  {
    "month": "2026-02",
    "total": 204,
    "excl_self": 164
  },
  {
    "month": "2026-03",
    "total": 207,
    "excl_self": 164
  },
  {
    "month": "2026-04",
    "total": 212,
    "excl_self": 168
  },
  {
    "month": "2026-05",
    "total": 215,
    "excl_self": 171
  },
  {
    "month": "2026-06",
    "total": 217,
    "excl_self": 173
  }
];

export const author_h_index = [
  {
    "month": "2020-01",
    "h": 0
  },
  {
    "month": "2021-01",
    "h": 1
  },
  {
    "month": "2022-05",
    "h": 2
  },
  {
    "month": "2023-06",
    "h": 3
  },
  {
    "month": "2024-01",
    "h": 4
  },
  {
    "month": "2024-07",
    "h": 5
  },
  {
    "month": "2025-04",
    "h": 6
  },
  {
    "month": "2025-05",
    "h": 7
  },
  {
    "month": "2025-10",
    "h": 8
  }
];

export const author_timeline_start = "2020-01";

export const current_month = "2026-06";
