#!/usr/bin/env python3
"""
Regenerate data.js and cv/*.tex from content.yaml.

Single source of truth: ../content.yaml (relative to this file).
Outputs:
  ../data.js                  -> website (researchData, talkData)
  ../cv/publications.tex      -> CV: Refereed Publications + \section{Preprints}
  ../cv/talks.tex             -> CV: Invited + \section{Lecture Series and Schools} + \section{Contributed Presentations}

Run: python3 scripts/build.py
"""

import json
from datetime import date, datetime
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "content.yaml"
OUT_DATA_JS = ROOT / "data.js"
OUT_PUBS_TEX = ROOT / "cv" / "publications.tex"
OUT_TALKS_TEX = ROOT / "cv" / "talks.tex"

GEN_HEADER_JS = (
    "// AUTO-GENERATED by scripts/build.py from content.yaml -- DO NOT EDIT.\n"
    "// To add a paper or talk, edit content.yaml and run: python3 scripts/build.py\n\n"
)
GEN_HEADER_TEX = (
    "% AUTO-GENERATED by scripts/build.py from content.yaml -- DO NOT EDIT.\n"
    "% To add an entry, edit content.yaml and run: python3 scripts/build.py\n\n"
)

DEFAULT_ROLE = {
    "invited": "Invited Speaker",
    "lectures": "Invited Guest Lecturer",
    "contributed": "",
}

CV_TALK_SECTIONS = [
    ("invited", None),
    ("lectures", "Lecture Series and Schools"),
    ("contributed", "Contributed Presentations"),
]


def parse_date(value):
    if isinstance(value, (date, datetime)):
        return value if isinstance(value, date) else value.date()
    if isinstance(value, str):
        return datetime.strptime(value, "%Y-%m-%d").date()
    raise ValueError(f"Bad date: {value!r}")


def pretty_month_year(d):
    return d.strftime("%B %Y")


def pretty_day_month_year(d):
    return f"{d.day} {d.strftime('%B %Y')}"


LATEX_ESCAPES = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def tex_escape(s):
    if s is None:
        return ""
    out = []
    for ch in str(s):
        out.append(LATEX_ESCAPES.get(ch, ch))
    return "".join(out)


def js_string(s):
    """Emit a JS double-quoted string literal."""
    return json.dumps("" if s is None else str(s), ensure_ascii=False)


# ----- publications -----

def pub_links(p):
    links = []
    if p.get("arxiv"):
        ax = str(p["arxiv"])
        links.append({"text": f"arXiv {ax}", "href": f"https://arxiv.org/abs/{ax}"})
    if p.get("journal") and p["journal"].get("href"):
        links.append({"text": p["journal"].get("name") or "Journal", "href": p["journal"]["href"]})
    if p.get("code") and p["code"].get("href"):
        links.append({"text": p["code"].get("name") or "Code", "href": p["code"]["href"]})
    for extra in p.get("links") or []:
        links.append({"text": extra["text"], "href": extra["href"]})
    return links


def render_research_js(pubs):
    visible = [p for p in pubs if not p.get("hidden")]
    visible.sort(key=lambda p: parse_date(p["date"]), reverse=True)
    lines = ["export const researchData = ["]
    for p in visible:
        d = parse_date(p["date"])
        links = pub_links(p)
        lines.append("  {")
        lines.append(f"    title: {js_string(p['title'])},")
        lines.append(f"    date: {js_string(d.isoformat())},")
        lines.append(f"    authors: {js_string(p['authors'])},")
        lines.append(f"    img: {js_string(p.get('img', ''))},")
        lines.append(f"    blurb: {js_string((p.get('blurb') or '').strip())},")
        lines.append("    links: [")
        for l in links:
            lines.append(f"      {{ text: {js_string(l['text'])}, href: {js_string(l['href'])} }},")
        lines.append("    ],")
        lines.append("  },")
    lines.append("];")
    return "\n".join(lines)


def pub_cventry(p):
    """Render one \\cventry line for a publication, mirroring main.tex format."""
    d = parse_date(p["date"])
    col1 = pretty_month_year(d)
    col2 = p["cv_title"] if p.get("cv_title") else tex_escape(p["title"])
    col3 = tex_escape(p["authors"])

    # arXiv link
    if p.get("arxiv"):
        ax = str(p["arxiv"])
        col4 = f"\\href{{https://arxiv.org/abs/arXiv:{ax}}}{{arXiv:{ax}}}"
    else:
        col4 = ""

    # Journal link
    j = p.get("journal") or {}
    if j.get("href") and j.get("name"):
        col5 = f"\\href{{{j['href']}}}{{{tex_escape(j['name'])}}}"
    elif j.get("name"):
        col5 = tex_escape(j["name"])
    else:
        col5 = ""

    # Associated code line
    c = p.get("code") or {}
    if c.get("href"):
        col6 = f"Associated code: \\url{{{c['href']}}}"
    elif p.get("cv_note"):
        col6 = tex_escape(p["cv_note"])
    else:
        col6 = ""

    return "\\cventry{" + col1 + "}{" + col2 + "}{" + col3 + "}{" + col4 + "}{" + col5 + "}{" + col6 + "}"


def render_publications_tex(pubs):
    in_cv = [p for p in pubs if not p.get("cv_hidden")]
    refereed = [p for p in in_cv if p.get("status") == "refereed"]
    preprints = [p for p in in_cv if p.get("status") == "preprint"]
    refereed.sort(key=lambda p: parse_date(p["date"]), reverse=True)
    preprints.sort(key=lambda p: parse_date(p["date"]), reverse=True)

    out = [GEN_HEADER_TEX]
    out.append("% Refereed Publications (\\section header is in main.tex)\n")
    for p in refereed:
        out.append(pub_cventry(p) + "\n\n")
    out.append("\\section{Preprints}\n\n")
    for p in preprints:
        out.append(pub_cventry(p) + "\n\n")
    return "".join(out)


# ----- talks -----

def talk_site_group(t):
    """Return the site group label for a talk, or None to skip the website."""
    if t.get("site_show") is False:
        return None
    if t.get("topic"):
        return t["topic"]
    if t.get("category") == "invited":
        return "Invited Talks"
    return None


def render_talks_js(talks):
    grouped = {}
    order = []
    for t in talks:
        g = talk_site_group(t)
        if g is None:
            continue
        if g not in grouped:
            grouped[g] = []
            order.append(g)
        grouped[g].append(t)

    # Order: "Invited Talks" first if present, then groups sorted by newest entry desc
    def group_key(g):
        newest = max(parse_date(t["date"]) for t in grouped[g])
        return (g != "Invited Talks", -newest.toordinal())

    order.sort(key=group_key)

    lines = ["export const talkData = ["]
    for g in order:
        items = sorted(grouped[g], key=lambda t: parse_date(t["date"]), reverse=True)
        lines.append("  {")
        lines.append(f"    category: {js_string(g)},")
        lines.append("    items: [")
        for t in items:
            d = parse_date(t["date"])
            lines.append("      {")
            lines.append(f"        featured: {'true' if t.get('featured') else 'false'},")
            lines.append(f"        title: {js_string(t['title'])},")
            lines.append(f"        where: {js_string(t.get('where', ''))},")
            lines.append(f"        date: {js_string(d.isoformat())},")
            slides = t.get("slides")
            video = t.get("video")
            lines.append(f"        slides: {js_string(slides) if slides else 'null'},")
            lines.append(f"        video: {js_string(video) if video else 'null'},")
            lines.append("      },")
        lines.append("    ],")
        lines.append("  },")
    lines.append("];")
    return "\n".join(lines)


def talk_cventry(t):
    d = parse_date(t["date"])
    col1 = t.get("cv_date_override") or pretty_day_month_year(d)
    col2 = tex_escape(t["title"])
    col3 = tex_escape(t.get("cv_event_name", ""))
    col4 = t.get("cv_event_href", "") or ""  # raw URL, not escaped (already a URL)
    col5 = ""

    role = t.get("role")
    if role is None:
        role = DEFAULT_ROLE.get(t.get("category", ""), "")
    location = t.get("location") or t.get("where") or ""
    virtual_suffix = " (Virtual)" if t.get("virtual") else ""
    pretty = t.get("cv_date_override") or pretty_day_month_year(d)

    if t.get("cv_description"):
        col6 = tex_escape(t["cv_description"])
    elif t.get("category") == "contributed":
        event = t.get("event")
        event_dates = t.get("event_dates") or pretty
        if event:
            col6 = f"{tex_escape(event)}, {tex_escape(event_dates)}, {tex_escape(location)}{virtual_suffix}"
        else:
            col6 = f"{tex_escape(location)}, {tex_escape(pretty)}{virtual_suffix}"
    else:
        prefix = f"{tex_escape(role)}, " if role else ""
        col6 = f"{prefix}{tex_escape(pretty)}, {tex_escape(location)}{virtual_suffix}"

    return "\\cventry{" + col1 + "}{" + col2 + "}{" + col3 + "}{" + col4 + "}{" + col5 + "}{" + col6 + "}"


def render_talks_tex(talks):
    in_cv = [t for t in talks if not t.get("cv_hidden") and t.get("category") in DEFAULT_ROLE]
    out = [GEN_HEADER_TEX]
    for cat, header in CV_TALK_SECTIONS:
        items = [t for t in in_cv if t.get("category") == cat]
        items.sort(key=lambda t: parse_date(t["date"]), reverse=True)
        if header:
            out.append(f"\\section{{{header}}}\n\n")
        else:
            out.append(f"% Invited Talks (\\section header is in main.tex)\n\n")
        for t in items:
            out.append(talk_cventry(t) + "\n\n")
    return "".join(out)


# ----- main -----

def main():
    with SRC.open() as f:
        data = yaml.safe_load(f)
    pubs = data.get("publications") or []
    talks = data.get("talks") or []

    OUT_PUBS_TEX.parent.mkdir(parents=True, exist_ok=True)

    js_out = GEN_HEADER_JS + render_research_js(pubs) + "\n\n" + render_talks_js(talks) + "\n"
    OUT_DATA_JS.write_text(js_out)
    OUT_PUBS_TEX.write_text(render_publications_tex(pubs))
    OUT_TALKS_TEX.write_text(render_talks_tex(talks))

    print(f"Wrote {OUT_DATA_JS.relative_to(ROOT)}")
    print(f"Wrote {OUT_PUBS_TEX.relative_to(ROOT)}")
    print(f"Wrote {OUT_TALKS_TEX.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
