#!/usr/bin/env python3
"""
Regenerate data.js and cv/*.tex from content.yaml.

Single source of truth: ../content.yaml (relative to this file).
Outputs:
  ../data.js                  -> website (researchData, talkData)
  ../cv/publications.tex      -> CV: Refereed Publications + \section{Preprints}
  ../cv/talks.tex             -> CV: Invited + \section{Lecture Series and Schools} + \section{Contributed Presentations}

Run: python3 scripts/build.py
"""

import json
import re
import urllib.error
import urllib.request
from datetime import date, datetime
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "content.yaml"
OUT_DATA_JS = ROOT / "data.js"
OUT_PUBS_TEX = ROOT / "cv" / "publications.tex"
OUT_TALKS_TEX = ROOT / "cv" / "talks.tex"
INSPIRE_CACHE = ROOT / "cache" / "inspire-bibtex"
INSPIRE_BIBTEX_URL = "https://inspirehep.net/api/literature?q=arxiv:{}&format=bibtex"
INSPIRE_RECORD_URL = "https://inspirehep.net/literature?q=arxiv:{}"

GEN_HEADER_JS = (
    "// AUTO-GENERATED by scripts/build.py from content.yaml -- DO NOT EDIT.\n"
    "// To add a paper or talk, edit content.yaml and run: python3 scripts/build.py\n\n"
)
GEN_HEADER_TEX = (
    "% AUTO-GENERATED by scripts/build.py from content.yaml -- DO NOT EDIT.\n"
    "% To add an entry, edit content.yaml and run: python3 scripts/build.py\n\n"
)

DEFAULT_ROLE = {
    "invited": "Invited Speaker",
    "lectures": "Invited Guest Lecturer",
    "contributed": "",
}

CV_TALK_SECTIONS = [
    ("invited", None),
    ("lectures", "Lecture Series and Schools"),
    ("contributed", "Contributed Presentations"),
]


def parse_date(value):
    if isinstance(value, (date, datetime)):
        return value if isinstance(value, date) else value.date()
    if isinstance(value, str):
        return datetime.strptime(value, "%Y-%m-%d").date()
    raise ValueError(f"Bad date: {value!r}")


def pretty_month_year(d):
    return d.strftime("%B %Y")


def pretty_day_month_year(d):
    return f"{d.day} {d.strftime('%B %Y')}"


LATEX_ESCAPES = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def tex_escape(s):
    if s is None:
        return ""
    out = []
    for ch in str(s):
        out.append(LATEX_ESCAPES.get(ch, ch))
    return "".join(out)


def js_string(s):
    """Emit a JS double-quoted string literal."""
    return json.dumps("" if s is None else str(s), ensure_ascii=False)


def js_value(v):
    """Emit any JSON-compatible value as a JS literal."""
    return json.dumps(v, ensure_ascii=False, indent=2)


_SLUG_RE = re.compile(r"[^a-z0-9]+")


def slugify(s):
    s = (s or "").lower()
    s = _SLUG_RE.sub("-", s).strip("-")
    return s or "item"


# ----- publications -----

def pub_links(p):
    links = []
    ax = str(p["arxiv"]) if p.get("arxiv") else None
    if ax:
        links.append({"text": "INSPIRE-HEP", "href": INSPIRE_RECORD_URL.format(ax)})
        links.append({"text": f"arXiv {ax}", "href": f"https://arxiv.org/abs/{ax}"})
    if p.get("journal") and p["journal"].get("href"):
        links.append({"text": p["journal"].get("name") or "Journal", "href": p["journal"]["href"]})
    if p.get("code") and p["code"].get("href"):
        links.append({"text": p["code"].get("name") or "Code", "href": p["code"]["href"]})
    for extra in p.get("links") or []:
        links.append({"text": extra["text"], "href": extra["href"]})
    return links


def fetch_bibtex(arxiv_id):
    """Return BibTeX from INSPIRE-HEP, cached on disk. Empty string on failure."""
    if not arxiv_id:
        return ""
    INSPIRE_CACHE.mkdir(parents=True, exist_ok=True)
    cache_file = INSPIRE_CACHE / f"{arxiv_id}.bib"
    if cache_file.exists():
        return cache_file.read_text().strip()
    url = INSPIRE_BIBTEX_URL.format(arxiv_id)
    try:
        req = urllib.request.Request(url, headers={"Accept": "application/x-bibtex"})
        with urllib.request.urlopen(req, timeout=8) as r:
            text = r.read().decode("utf-8", errors="replace").strip()
        if text and text.startswith("@"):
            cache_file.write_text(text + "\n")
            return text
        print(f"  [bibtex] empty/invalid response for arXiv:{arxiv_id}")
    except (urllib.error.URLError, TimeoutError, OSError) as e:
        print(f"  [bibtex] fetch failed for arXiv:{arxiv_id} ({e})")
    return ""


def derive_pub_slug(p, used):
    if p.get("slug"):
        return p["slug"]
    base = slugify((p.get("title") or "").split(":")[0]) or slugify(p.get("title") or "")
    base = base.split("-")[0] if base else "paper"
    slug = base
    n = 2
    while slug in used:
        slug = f"{base}-{n}"
        n += 1
    return slug


def derive_talk_id(t, used):
    if t.get("id"):
        return t["id"]
    base = f"{slugify(t.get('title','talk'))[:40]}-{parse_date(t['date']).isoformat()}"
    tid = base
    n = 2
    while tid in used:
        tid = f"{base}-{n}"
        n += 1
    return tid


def build_publications(pubs):
    """Return list of dicts ready for JSON, with slugs assigned."""
    visible = [p for p in pubs if not p.get("hidden")]
    visible.sort(key=lambda p: parse_date(p["date"]), reverse=True)
    used = set()
    out = []
    for p in visible:
        slug = derive_pub_slug(p, used)
        used.add(slug)
        d = parse_date(p["date"])
        bibtex = (p.get("bibtex") or "").strip()
        if not bibtex and p.get("arxiv"):
            bibtex = fetch_bibtex(str(p["arxiv"]))
        out.append({
            "slug": slug,
            "title": p["title"],
            "date": d.isoformat(),
            "authors": p["authors"],
            "img": p.get("img", ""),
            "blurb": (p.get("blurb") or "").strip(),
            "abstract": (p.get("abstract") or "").strip(),
            "tags": p.get("tags") or [],
            "featured": bool(p.get("featured")),
            "joke": bool(p.get("joke")),
            "status": p.get("status", "preprint"),
            "bibtex": bibtex,
            "links": pub_links(p),
            "talks": [],  # filled in by attach_talks
        })
    return out


# Topic / title-keyword -> publication slug. Used when a talk doesn't have an
# explicit `paper:` field, to auto-cross-link talks back to their paper.
TOPIC_PAPER_MAP = {
    "Pareto Frontier": "pareto",
    "Re-Normalizing Flows": "rdf",
    "SPECTER – Spectral EMD": "specter",
    "Muon Beam Dumps": "muon-beam-dump",
    "Can You Hear the Shape of a Jet?": "shaper",
    "Moment Pooling": "moments",
    "Frequentist Way – Calibration & Correlation": "frequentist-way",
}

TITLE_KEYWORD_PAPER_MAP = [
    ("HD Sense", "hdsense"),
    ("HDSense", "hdsense"),
    ("Resummed Distribution Functions", "rdf"),
    ("Re-Normalizing Flows", "rdf"),
    ("Pareto Frontier", "pareto"),
    ("Unisolated Upsilons", "upsilons"),
    ("Anomaly Detection", "upsilons"),
    ("Moments of Clarity", "moments"),
    ("Moment Pooling", "moments"),
    ("Shape of Jets", "shaper"),
    ("Hear the Shape", "shaper"),
    ("Frequentist Way", "frequentist-way"),
    ("Muon Beam", "muon-beam-dump"),
    ("SPECTER", "specter"),
    ("Vector-Like Quark", "vlq"),
    ("Seeing Double", "seeing-double"),
    ("Bias and Priors", "calibration-priors"),
]


def infer_paper_slug(t, pub_slugs):
    if t.get("paper"):
        return t["paper"] if t["paper"] in pub_slugs else None
    if t.get("topic") and t["topic"] in TOPIC_PAPER_MAP:
        slug = TOPIC_PAPER_MAP[t["topic"]]
        return slug if slug in pub_slugs else None
    title = t.get("title", "")
    for needle, slug in TITLE_KEYWORD_PAPER_MAP:
        if needle.lower() in title.lower() and slug in pub_slugs:
            return slug
    return None


def build_talks(talks, pub_slugs):
    """Return list of dicts ready for JSON for the website.
    Every talk shows by default; opt out per-entry with `site_show: false`."""
    visible = [t for t in talks if t.get("site_show") is not False]
    used_ids = set()
    out = []
    for t in sorted(visible, key=lambda t: parse_date(t["date"]), reverse=True):
        d = parse_date(t["date"])
        tid = derive_talk_id(t, used_ids)
        used_ids.add(tid)
        paper = infer_paper_slug(t, pub_slugs)
        out.append({
            "id": tid,
            "title": t["title"],
            "where": t.get("where", ""),
            "date": d.isoformat(),
            "category": t.get("category", "contributed"),
            "topic": t.get("topic", ""),
            "slides": t.get("slides") or None,
            "video": t.get("video") or None,
            "featured": bool(t.get("featured")),
            "paper": paper,
            "abstract": (t.get("abstract") or "").strip(),
        })
    return out


def attach_talks_to_pubs(pubs_out, talks_out):
    by_slug = {p["slug"]: p for p in pubs_out}
    for t in talks_out:
        if t["paper"] and t["paper"] in by_slug:
            by_slug[t["paper"]]["talks"].append(t["id"])


def build_software(software):
    out = []
    for s in software or []:
        out.append({
            "name": s["name"],
            "role": s.get("role", ""),
            "install": s.get("install", ""),
            "github": s.get("github", ""),
            "homepage": s.get("homepage", ""),
            "paper": s.get("paper") or None,
            "blurb": (s.get("blurb") or "").strip(),
        })
    return out


def render_data_js(pubs_out, talks_out, software_out):
    return (
        GEN_HEADER_JS
        + "export const researchData = " + js_value(pubs_out) + ";\n\n"
        + "export const talkData = " + js_value(talks_out) + ";\n\n"
        + "export const softwareData = " + js_value(software_out) + ";\n"
    )


def pub_cventry(p):
    """Render one \\cventry line for a publication, mirroring main.tex format."""
    d = parse_date(p["date"])
    col1 = pretty_month_year(d)
    col2 = p["cv_title"] if p.get("cv_title") else tex_escape(p["title"])
    col3 = tex_escape(p["authors"])

    # arXiv link
    if p.get("arxiv"):
        ax = str(p["arxiv"])
        col4 = f"\\href{{https://arxiv.org/abs/arXiv:{ax}}}{{arXiv:{ax}}}"
    else:
        col4 = ""

    # Journal link
    j = p.get("journal") or {}
    if j.get("href") and j.get("name"):
        col5 = f"\\href{{{j['href']}}}{{{tex_escape(j['name'])}}}"
    elif j.get("name"):
        col5 = tex_escape(j["name"])
    else:
        col5 = ""

    # Associated code line
    c = p.get("code") or {}
    if c.get("href"):
        col6 = f"Associated code: \\url{{{c['href']}}}"
    elif p.get("cv_note"):
        col6 = tex_escape(p["cv_note"])
    else:
        col6 = ""

    return "\\cventry{" + col1 + "}{" + col2 + "}{" + col3 + "}{" + col4 + "}{" + col5 + "}{" + col6 + "}"


def render_publications_tex(pubs):
    in_cv = [p for p in pubs if not p.get("cv_hidden")]
    refereed = [p for p in in_cv if p.get("status") == "refereed"]
    preprints = [p for p in in_cv if p.get("status") == "preprint"]
    refereed.sort(key=lambda p: parse_date(p["date"]), reverse=True)
    preprints.sort(key=lambda p: parse_date(p["date"]), reverse=True)

    out = [GEN_HEADER_TEX]
    out.append("% Refereed Publications (\\section header is in main.tex)\n")
    for p in refereed:
        out.append(pub_cventry(p) + "\n\n")
    out.append("\\section{Preprints}\n\n")
    for p in preprints:
        out.append(pub_cventry(p) + "\n\n")
    return "".join(out)


# ----- talks (CV) -----

def talk_cventry(t):
    d = parse_date(t["date"])
    col1 = t.get("cv_date_override") or pretty_day_month_year(d)
    col2 = tex_escape(t["title"])
    col3 = tex_escape(t.get("cv_event_name", ""))
    col4 = t.get("cv_event_href", "") or ""  # raw URL, not escaped (already a URL)
    col5 = ""

    role = t.get("role")
    if role is None:
        role = DEFAULT_ROLE.get(t.get("category", ""), "")
    location = t.get("location") or t.get("where") or ""
    virtual_suffix = " (Virtual)" if t.get("virtual") else ""
    pretty = t.get("cv_date_override") or pretty_day_month_year(d)

    if t.get("cv_description"):
        col6 = tex_escape(t["cv_description"])
    elif t.get("category") == "contributed":
        event = t.get("event")
        event_dates = t.get("event_dates") or pretty
        if event:
            col6 = f"{tex_escape(event)}, {tex_escape(event_dates)}, {tex_escape(location)}{virtual_suffix}"
        else:
            col6 = f"{tex_escape(location)}, {tex_escape(pretty)}{virtual_suffix}"
    else:
        prefix = f"{tex_escape(role)}, " if role else ""
        col6 = f"{prefix}{tex_escape(pretty)}, {tex_escape(location)}{virtual_suffix}"

    return "\\cventry{" + col1 + "}{" + col2 + "}{" + col3 + "}{" + col4 + "}{" + col5 + "}{" + col6 + "}"


def render_talks_tex(talks):
    in_cv = [t for t in talks if not t.get("cv_hidden") and t.get("category") in DEFAULT_ROLE]
    out = [GEN_HEADER_TEX]
    for cat, header in CV_TALK_SECTIONS:
        items = [t for t in in_cv if t.get("category") == cat]
        items.sort(key=lambda t: parse_date(t["date"]), reverse=True)
        if header:
            out.append(f"\\section{{{header}}}\n\n")
        else:
            out.append(f"% Invited Talks (\\section header is in main.tex)\n\n")
        for t in items:
            out.append(talk_cventry(t) + "\n\n")
    return "".join(out)


# ----- main -----

def bump_main_js_cachebust(version):
    """Update the version query string on the data.js import in js/main.js."""
    main_js = ROOT / "js" / "main.js"
    s = main_js.read_text()
    new = re.sub(
        r"from '\.\./data\.js(?:\?v=[^']*)?';",
        f"from '../data.js?v={version}';",
        s,
        count=1,
    )
    if new != s:
        main_js.write_text(new)


def main():
    with SRC.open() as f:
        data = yaml.safe_load(f)
    pubs = data.get("publications") or []
    talks = data.get("talks") or []
    software = data.get("software") or []

    OUT_PUBS_TEX.parent.mkdir(parents=True, exist_ok=True)

    pubs_out = build_publications(pubs)
    talks_out = build_talks(talks, {p["slug"] for p in pubs_out})
    attach_talks_to_pubs(pubs_out, talks_out)
    software_out = build_software(software)

    js_text = render_data_js(pubs_out, talks_out, software_out)
    OUT_DATA_JS.write_text(js_text)
    OUT_PUBS_TEX.write_text(render_publications_tex(pubs))
    OUT_TALKS_TEX.write_text(render_talks_tex(talks))

    # Version query string busts the browser's ES-module cache on rebuild.
    import hashlib
    version = hashlib.md5(js_text.encode()).hexdigest()[:8]
    bump_main_js_cachebust(version)

    print(f"Wrote {OUT_DATA_JS.relative_to(ROOT)}")
    print(f"Wrote {OUT_PUBS_TEX.relative_to(ROOT)}")
    print(f"Wrote {OUT_TALKS_TEX.relative_to(ROOT)}")
    print(f"Cache-bust: data.js?v={version}")


if __name__ == "__main__":
    main()
