# imports
import json
import re
import urllib.error
import urllib.request
from datetime import date, datetime
from pathlib import Path

# repo paths
ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "content.yaml"
OUT_DATA_JS = ROOT / "data.js"
OUT_PUBS_TEX = ROOT / "cv" / "publications.tex"
OUT_TALKS_TEX = ROOT / "cv" / "talks.tex"

# CV latex source and the served pdf
CV_MAIN_TEX = ROOT / "main.tex"
CV_PDF_OUT = ROOT / "assets" / "pdf" / "rikab_CV.pdf"

# DO-NOT-EDIT banners (Reminders for myself)
GEN_HEADER_JS = (
    "// AUTO-GENERATED by scripts/build.py from content.yaml -- DO NOT EDIT.\n"
    "// To add a paper or talk, edit content.yaml and run: python3 scripts/build.py\n\n"
)
GEN_HEADER_TEX = ( 
    "% AUTO-GENERATED by scripts/build.py from content.yaml -- DO NOT EDIT.\n"
    "% To add an entry, edit content.yaml and run: python3 scripts/build.py\n\n"
)


# get date
def parse_date(value):
    if isinstance(value, (date, datetime)):
        return value if isinstance(value, date) else value.date()
    if isinstance(value, str):
        return datetime.strptime(value, "%Y-%m-%d").date()
    raise ValueError(f"Bad date: {value!r}")


# format date as month year, eg "May 2026"
def pretty_month_year(d):
    return d.strftime("%B %Y")


# format date as day month year, eg "25 May 2026"
def pretty_day_month_year(d):
    return f"{d.day} {d.strftime('%B %Y')}"


# character to latex replacement
LATEX_ESCAPES = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


# latex-escape special character
def tex_escape(s):
    if s is None:
        return ""
    out = []
    for ch in str(s):
        out.append(LATEX_ESCAPES.get(ch, ch))
    return "".join(out)


# json-encoded string for embedding in js
def js_string(s):
    return json.dumps("" if s is None else str(s), ensure_ascii=False)


# json-encoded value, pretty-printed
def js_value(v):
    return json.dumps(v, ensure_ascii=False, indent=2)


# non-alnum runs to single dash
_ID_RE = re.compile(r"[^a-z0-9]+")


# url-safe id, fallback "item"
def make_id(s):
    s = (s or "").lower()
    s = _ID_RE.sub("-", s).strip("-")
    return s or "item"


# urllib wrapper for json GETs
def http_get_json(url, timeout=10):
    req = urllib.request.Request(url, headers={"Accept": "application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read().decode("utf-8", errors="replace"))


# YYYY-MM list, start to end
def month_range(start_ym, end_ym):
    sy, sm = int(start_ym[:4]), int(start_ym[5:7])
    ey, em = int(end_ym[:4]), int(end_ym[5:7])
    out = []
    y, m = sy, sm
    while (y, m) <= (ey, em):
        out.append(f"{y:04d}-{m:02d}")
        m += 1
        if m > 12:
            m = 1
            y += 1
    return out
